/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: analogInTypeB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "analogInTypeB.pb-c.h"
void   analog_in_type_b__channel_config__init
                     (AnalogInTypeB__ChannelConfig         *message)
{
  static const AnalogInTypeB__ChannelConfig init_value = ANALOG_IN_TYPE_B__CHANNEL_CONFIG__INIT;
  *message = init_value;
}
size_t analog_in_type_b__channel_config__get_packed_size
                     (const AnalogInTypeB__ChannelConfig *message)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__channel_config__pack
                     (const AnalogInTypeB__ChannelConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__channel_config__pack_to_buffer
                     (const AnalogInTypeB__ChannelConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ChannelConfig *
       analog_in_type_b__channel_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ChannelConfig *)
     protobuf_c_message_unpack (&analog_in_type_b__channel_config__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__channel_config__free_unpacked
                     (AnalogInTypeB__ChannelConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__channel_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__channel_group_specification__init
                     (AnalogInTypeB__ChannelGroupSpecification         *message)
{
  static const AnalogInTypeB__ChannelGroupSpecification init_value = ANALOG_IN_TYPE_B__CHANNEL_GROUP_SPECIFICATION__INIT;
  *message = init_value;
}
size_t analog_in_type_b__channel_group_specification__get_packed_size
                     (const AnalogInTypeB__ChannelGroupSpecification *message)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_group_specification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__channel_group_specification__pack
                     (const AnalogInTypeB__ChannelGroupSpecification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_group_specification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__channel_group_specification__pack_to_buffer
                     (const AnalogInTypeB__ChannelGroupSpecification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__channel_group_specification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ChannelGroupSpecification *
       analog_in_type_b__channel_group_specification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ChannelGroupSpecification *)
     protobuf_c_message_unpack (&analog_in_type_b__channel_group_specification__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__channel_group_specification__free_unpacked
                     (AnalogInTypeB__ChannelGroupSpecification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__channel_group_specification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_set__init
                     (AnalogInTypeB__ConfigurationSet         *message)
{
  static const AnalogInTypeB__ConfigurationSet init_value = ANALOG_IN_TYPE_B__CONFIGURATION_SET__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_set__get_packed_size
                     (const AnalogInTypeB__ConfigurationSet *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_set__pack
                     (const AnalogInTypeB__ConfigurationSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_set__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationSet *
       analog_in_type_b__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationSet *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_set__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_set__free_unpacked
                     (AnalogInTypeB__ConfigurationSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_set_response__init
                     (AnalogInTypeB__ConfigurationSetResponse         *message)
{
  static const AnalogInTypeB__ConfigurationSetResponse init_value = ANALOG_IN_TYPE_B__CONFIGURATION_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_set_response__get_packed_size
                     (const AnalogInTypeB__ConfigurationSetResponse *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_set_response__pack
                     (const AnalogInTypeB__ConfigurationSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_set_response__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationSetResponse *
       analog_in_type_b__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationSetResponse *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_set_response__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_set_response__free_unpacked
                     (AnalogInTypeB__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_get__init
                     (AnalogInTypeB__ConfigurationGet         *message)
{
  static const AnalogInTypeB__ConfigurationGet init_value = ANALOG_IN_TYPE_B__CONFIGURATION_GET__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_get__get_packed_size
                     (const AnalogInTypeB__ConfigurationGet *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_get__pack
                     (const AnalogInTypeB__ConfigurationGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_get__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationGet *
       analog_in_type_b__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationGet *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_get__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_get__free_unpacked
                     (AnalogInTypeB__ConfigurationGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_get_response__init
                     (AnalogInTypeB__ConfigurationGetResponse         *message)
{
  static const AnalogInTypeB__ConfigurationGetResponse init_value = ANALOG_IN_TYPE_B__CONFIGURATION_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_get_response__get_packed_size
                     (const AnalogInTypeB__ConfigurationGetResponse *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_get_response__pack
                     (const AnalogInTypeB__ConfigurationGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_get_response__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationGetResponse *
       analog_in_type_b__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationGetResponse *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_get_response__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_get_response__free_unpacked
                     (AnalogInTypeB__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_describe__init
                     (AnalogInTypeB__ConfigurationDescribe         *message)
{
  static const AnalogInTypeB__ConfigurationDescribe init_value = ANALOG_IN_TYPE_B__CONFIGURATION_DESCRIBE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_describe__get_packed_size
                     (const AnalogInTypeB__ConfigurationDescribe *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_describe__pack
                     (const AnalogInTypeB__ConfigurationDescribe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_describe__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationDescribe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationDescribe *
       analog_in_type_b__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationDescribe *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_describe__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_describe__free_unpacked
                     (AnalogInTypeB__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__configuration_describe_response__init
                     (AnalogInTypeB__ConfigurationDescribeResponse         *message)
{
  static const AnalogInTypeB__ConfigurationDescribeResponse init_value = ANALOG_IN_TYPE_B__CONFIGURATION_DESCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__configuration_describe_response__get_packed_size
                     (const AnalogInTypeB__ConfigurationDescribeResponse *message)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__configuration_describe_response__pack
                     (const AnalogInTypeB__ConfigurationDescribeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__configuration_describe_response__pack_to_buffer
                     (const AnalogInTypeB__ConfigurationDescribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__ConfigurationDescribeResponse *
       analog_in_type_b__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__ConfigurationDescribeResponse *)
     protobuf_c_message_unpack (&analog_in_type_b__configuration_describe_response__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__configuration_describe_response__free_unpacked
                     (AnalogInTypeB__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__configuration_describe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__function_control_get__init
                     (AnalogInTypeB__FunctionControlGet         *message)
{
  static const AnalogInTypeB__FunctionControlGet init_value = ANALOG_IN_TYPE_B__FUNCTION_CONTROL_GET__INIT;
  *message = init_value;
}
size_t analog_in_type_b__function_control_get__get_packed_size
                     (const AnalogInTypeB__FunctionControlGet *message)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__function_control_get__pack
                     (const AnalogInTypeB__FunctionControlGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__function_control_get__pack_to_buffer
                     (const AnalogInTypeB__FunctionControlGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__FunctionControlGet *
       analog_in_type_b__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__FunctionControlGet *)
     protobuf_c_message_unpack (&analog_in_type_b__function_control_get__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__function_control_get__free_unpacked
                     (AnalogInTypeB__FunctionControlGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__function_control_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__function_control_set__init
                     (AnalogInTypeB__FunctionControlSet         *message)
{
  static const AnalogInTypeB__FunctionControlSet init_value = ANALOG_IN_TYPE_B__FUNCTION_CONTROL_SET__INIT;
  *message = init_value;
}
size_t analog_in_type_b__function_control_set__get_packed_size
                     (const AnalogInTypeB__FunctionControlSet *message)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__function_control_set__pack
                     (const AnalogInTypeB__FunctionControlSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__function_control_set__pack_to_buffer
                     (const AnalogInTypeB__FunctionControlSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__FunctionControlSet *
       analog_in_type_b__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__FunctionControlSet *)
     protobuf_c_message_unpack (&analog_in_type_b__function_control_set__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__function_control_set__free_unpacked
                     (AnalogInTypeB__FunctionControlSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__function_control_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__function_control_get_response__init
                     (AnalogInTypeB__FunctionControlGetResponse         *message)
{
  static const AnalogInTypeB__FunctionControlGetResponse init_value = ANALOG_IN_TYPE_B__FUNCTION_CONTROL_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__function_control_get_response__get_packed_size
                     (const AnalogInTypeB__FunctionControlGetResponse *message)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__function_control_get_response__pack
                     (const AnalogInTypeB__FunctionControlGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__function_control_get_response__pack_to_buffer
                     (const AnalogInTypeB__FunctionControlGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__FunctionControlGetResponse *
       analog_in_type_b__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__FunctionControlGetResponse *)
     protobuf_c_message_unpack (&analog_in_type_b__function_control_get_response__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__function_control_get_response__free_unpacked
                     (AnalogInTypeB__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__function_control_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__function_control_set_response__init
                     (AnalogInTypeB__FunctionControlSetResponse         *message)
{
  static const AnalogInTypeB__FunctionControlSetResponse init_value = ANALOG_IN_TYPE_B__FUNCTION_CONTROL_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t analog_in_type_b__function_control_set_response__get_packed_size
                     (const AnalogInTypeB__FunctionControlSetResponse *message)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__function_control_set_response__pack
                     (const AnalogInTypeB__FunctionControlSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__function_control_set_response__pack_to_buffer
                     (const AnalogInTypeB__FunctionControlSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__FunctionControlSetResponse *
       analog_in_type_b__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__FunctionControlSetResponse *)
     protobuf_c_message_unpack (&analog_in_type_b__function_control_set_response__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__function_control_set_response__free_unpacked
                     (AnalogInTypeB__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__function_control_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__stream_control_start__init
                     (AnalogInTypeB__StreamControlStart         *message)
{
  static const AnalogInTypeB__StreamControlStart init_value = ANALOG_IN_TYPE_B__STREAM_CONTROL_START__INIT;
  *message = init_value;
}
size_t analog_in_type_b__stream_control_start__get_packed_size
                     (const AnalogInTypeB__StreamControlStart *message)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_control_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__stream_control_start__pack
                     (const AnalogInTypeB__StreamControlStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_control_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__stream_control_start__pack_to_buffer
                     (const AnalogInTypeB__StreamControlStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_control_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__StreamControlStart *
       analog_in_type_b__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__StreamControlStart *)
     protobuf_c_message_unpack (&analog_in_type_b__stream_control_start__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__stream_control_start__free_unpacked
                     (AnalogInTypeB__StreamControlStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__stream_control_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__sample_group__init
                     (AnalogInTypeB__SampleGroup         *message)
{
  static const AnalogInTypeB__SampleGroup init_value = ANALOG_IN_TYPE_B__SAMPLE_GROUP__INIT;
  *message = init_value;
}
size_t analog_in_type_b__sample_group__get_packed_size
                     (const AnalogInTypeB__SampleGroup *message)
{
  assert(message->base.descriptor == &analog_in_type_b__sample_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__sample_group__pack
                     (const AnalogInTypeB__SampleGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__sample_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__sample_group__pack_to_buffer
                     (const AnalogInTypeB__SampleGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__sample_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__SampleGroup *
       analog_in_type_b__sample_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__SampleGroup *)
     protobuf_c_message_unpack (&analog_in_type_b__sample_group__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__sample_group__free_unpacked
                     (AnalogInTypeB__SampleGroup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__sample_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analog_in_type_b__stream_data__init
                     (AnalogInTypeB__StreamData         *message)
{
  static const AnalogInTypeB__StreamData init_value = ANALOG_IN_TYPE_B__STREAM_DATA__INIT;
  *message = init_value;
}
size_t analog_in_type_b__stream_data__get_packed_size
                     (const AnalogInTypeB__StreamData *message)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analog_in_type_b__stream_data__pack
                     (const AnalogInTypeB__StreamData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analog_in_type_b__stream_data__pack_to_buffer
                     (const AnalogInTypeB__StreamData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analog_in_type_b__stream_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnalogInTypeB__StreamData *
       analog_in_type_b__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnalogInTypeB__StreamData *)
     protobuf_c_message_unpack (&analog_in_type_b__stream_data__descriptor,
                                allocator, len, data);
}
void   analog_in_type_b__stream_data__free_unpacked
                     (AnalogInTypeB__StreamData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analog_in_type_b__stream_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor analog_in_type_b__channel_config__field_descriptors[3] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__ChannelConfig, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__ChannelConfig, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gain",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__ChannelConfig, gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__channel_config__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  2,   /* field[2] = gain */
  1,   /* field[1] = sample_rate */
};
static const ProtobufCIntRange analog_in_type_b__channel_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor analog_in_type_b__channel_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ChannelConfig",
  "ChannelConfig",
  "AnalogInTypeB__ChannelConfig",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ChannelConfig),
  3,
  analog_in_type_b__channel_config__field_descriptors,
  analog_in_type_b__channel_config__field_indices_by_name,
  1,  analog_in_type_b__channel_config__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__channel_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__channel_group_specification__field_descriptors[3] =
{
  {
    "channels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AnalogInTypeB__ChannelGroupSpecification, n_channels),
    offsetof(AnalogInTypeB__ChannelGroupSpecification, channels),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_sample_rates",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(AnalogInTypeB__ChannelGroupSpecification, n_supported_sample_rates),
    offsetof(AnalogInTypeB__ChannelGroupSpecification, supported_sample_rates),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_gains",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AnalogInTypeB__ChannelGroupSpecification, n_supported_gains),
    offsetof(AnalogInTypeB__ChannelGroupSpecification, supported_gains),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__channel_group_specification__field_indices_by_name[] = {
  0,   /* field[0] = channels */
  2,   /* field[2] = supported_gains */
  1,   /* field[1] = supported_sample_rates */
};
static const ProtobufCIntRange analog_in_type_b__channel_group_specification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor analog_in_type_b__channel_group_specification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ChannelGroupSpecification",
  "ChannelGroupSpecification",
  "AnalogInTypeB__ChannelGroupSpecification",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ChannelGroupSpecification),
  3,
  analog_in_type_b__channel_group_specification__field_descriptors,
  analog_in_type_b__channel_group_specification__field_indices_by_name,
  1,  analog_in_type_b__channel_group_specification__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__channel_group_specification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__configuration_set__field_descriptors[1] =
{
  {
    "channelConfig",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AnalogInTypeB__ConfigurationSet, n_channelconfig),
    offsetof(AnalogInTypeB__ConfigurationSet, channelconfig),
    &analog_in_type_b__channel_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__configuration_set__field_indices_by_name[] = {
  0,   /* field[0] = channelConfig */
};
static const ProtobufCIntRange analog_in_type_b__configuration_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__configuration_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationSet",
  "ConfigurationSet",
  "AnalogInTypeB__ConfigurationSet",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationSet),
  1,
  analog_in_type_b__configuration_set__field_descriptors,
  analog_in_type_b__configuration_set__field_indices_by_name,
  1,  analog_in_type_b__configuration_set__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__configuration_set_response__field_descriptors NULL
#define analog_in_type_b__configuration_set_response__field_indices_by_name NULL
#define analog_in_type_b__configuration_set_response__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__configuration_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationSetResponse",
  "ConfigurationSetResponse",
  "AnalogInTypeB__ConfigurationSetResponse",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationSetResponse),
  0,
  analog_in_type_b__configuration_set_response__field_descriptors,
  analog_in_type_b__configuration_set_response__field_indices_by_name,
  0,  analog_in_type_b__configuration_set_response__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__configuration_get__field_descriptors NULL
#define analog_in_type_b__configuration_get__field_indices_by_name NULL
#define analog_in_type_b__configuration_get__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__configuration_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationGet",
  "ConfigurationGet",
  "AnalogInTypeB__ConfigurationGet",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationGet),
  0,
  analog_in_type_b__configuration_get__field_descriptors,
  analog_in_type_b__configuration_get__field_indices_by_name,
  0,  analog_in_type_b__configuration_get__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__configuration_get_response__field_descriptors[1] =
{
  {
    "channelConfig",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AnalogInTypeB__ConfigurationGetResponse, n_channelconfig),
    offsetof(AnalogInTypeB__ConfigurationGetResponse, channelconfig),
    &analog_in_type_b__channel_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__configuration_get_response__field_indices_by_name[] = {
  0,   /* field[0] = channelConfig */
};
static const ProtobufCIntRange analog_in_type_b__configuration_get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__configuration_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationGetResponse",
  "ConfigurationGetResponse",
  "AnalogInTypeB__ConfigurationGetResponse",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationGetResponse),
  1,
  analog_in_type_b__configuration_get_response__field_descriptors,
  analog_in_type_b__configuration_get_response__field_indices_by_name,
  1,  analog_in_type_b__configuration_get_response__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__configuration_describe__field_descriptors NULL
#define analog_in_type_b__configuration_describe__field_indices_by_name NULL
#define analog_in_type_b__configuration_describe__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__configuration_describe__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationDescribe",
  "ConfigurationDescribe",
  "AnalogInTypeB__ConfigurationDescribe",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationDescribe),
  0,
  analog_in_type_b__configuration_describe__field_descriptors,
  analog_in_type_b__configuration_describe__field_indices_by_name,
  0,  analog_in_type_b__configuration_describe__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_describe__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__configuration_describe_response__field_descriptors[1] =
{
  {
    "channelSpecification",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AnalogInTypeB__ConfigurationDescribeResponse, n_channelspecification),
    offsetof(AnalogInTypeB__ConfigurationDescribeResponse, channelspecification),
    &analog_in_type_b__channel_group_specification__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__configuration_describe_response__field_indices_by_name[] = {
  0,   /* field[0] = channelSpecification */
};
static const ProtobufCIntRange analog_in_type_b__configuration_describe_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__configuration_describe_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.ConfigurationDescribeResponse",
  "ConfigurationDescribeResponse",
  "AnalogInTypeB__ConfigurationDescribeResponse",
  "analogInTypeB",
  sizeof(AnalogInTypeB__ConfigurationDescribeResponse),
  1,
  analog_in_type_b__configuration_describe_response__field_descriptors,
  analog_in_type_b__configuration_describe_response__field_indices_by_name,
  1,  analog_in_type_b__configuration_describe_response__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__configuration_describe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__function_control_get__field_descriptors NULL
#define analog_in_type_b__function_control_get__field_indices_by_name NULL
#define analog_in_type_b__function_control_get__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__function_control_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.FunctionControlGet",
  "FunctionControlGet",
  "AnalogInTypeB__FunctionControlGet",
  "analogInTypeB",
  sizeof(AnalogInTypeB__FunctionControlGet),
  0,
  analog_in_type_b__function_control_get__field_descriptors,
  analog_in_type_b__function_control_get__field_indices_by_name,
  0,  analog_in_type_b__function_control_get__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__function_control_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__function_control_set__field_descriptors NULL
#define analog_in_type_b__function_control_set__field_indices_by_name NULL
#define analog_in_type_b__function_control_set__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__function_control_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.FunctionControlSet",
  "FunctionControlSet",
  "AnalogInTypeB__FunctionControlSet",
  "analogInTypeB",
  sizeof(AnalogInTypeB__FunctionControlSet),
  0,
  analog_in_type_b__function_control_set__field_descriptors,
  analog_in_type_b__function_control_set__field_indices_by_name,
  0,  analog_in_type_b__function_control_set__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__function_control_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__function_control_get_response__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(AnalogInTypeB__FunctionControlGetResponse, n_value),
    offsetof(AnalogInTypeB__FunctionControlGetResponse, value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__function_control_get_response__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange analog_in_type_b__function_control_get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__function_control_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.FunctionControlGetResponse",
  "FunctionControlGetResponse",
  "AnalogInTypeB__FunctionControlGetResponse",
  "analogInTypeB",
  sizeof(AnalogInTypeB__FunctionControlGetResponse),
  1,
  analog_in_type_b__function_control_get_response__field_descriptors,
  analog_in_type_b__function_control_get_response__field_indices_by_name,
  1,  analog_in_type_b__function_control_get_response__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__function_control_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analog_in_type_b__function_control_set_response__field_descriptors NULL
#define analog_in_type_b__function_control_set_response__field_indices_by_name NULL
#define analog_in_type_b__function_control_set_response__number_ranges NULL
const ProtobufCMessageDescriptor analog_in_type_b__function_control_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.FunctionControlSetResponse",
  "FunctionControlSetResponse",
  "AnalogInTypeB__FunctionControlSetResponse",
  "analogInTypeB",
  sizeof(AnalogInTypeB__FunctionControlSetResponse),
  0,
  analog_in_type_b__function_control_set_response__field_descriptors,
  analog_in_type_b__function_control_set_response__field_indices_by_name,
  0,  analog_in_type_b__function_control_set_response__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__function_control_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__stream_control_start__field_descriptors[1] =
{
  {
    "channelMask",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__StreamControlStart, channelmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__stream_control_start__field_indices_by_name[] = {
  0,   /* field[0] = channelMask */
};
static const ProtobufCIntRange analog_in_type_b__stream_control_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__stream_control_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.StreamControlStart",
  "StreamControlStart",
  "AnalogInTypeB__StreamControlStart",
  "analogInTypeB",
  sizeof(AnalogInTypeB__StreamControlStart),
  1,
  analog_in_type_b__stream_control_start__field_descriptors,
  analog_in_type_b__stream_control_start__field_indices_by_name,
  1,  analog_in_type_b__stream_control_start__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__stream_control_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__sample_group__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__SampleGroup, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baseChannel",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AnalogInTypeB__SampleGroup, basechannel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(AnalogInTypeB__SampleGroup, n_value),
    offsetof(AnalogInTypeB__SampleGroup, value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__sample_group__field_indices_by_name[] = {
  1,   /* field[1] = baseChannel */
  0,   /* field[0] = timestamp */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange analog_in_type_b__sample_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor analog_in_type_b__sample_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.SampleGroup",
  "SampleGroup",
  "AnalogInTypeB__SampleGroup",
  "analogInTypeB",
  sizeof(AnalogInTypeB__SampleGroup),
  3,
  analog_in_type_b__sample_group__field_descriptors,
  analog_in_type_b__sample_group__field_indices_by_name,
  1,  analog_in_type_b__sample_group__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__sample_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analog_in_type_b__stream_data__field_descriptors[1] =
{
  {
    "samples",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AnalogInTypeB__StreamData, n_samples),
    offsetof(AnalogInTypeB__StreamData, samples),
    &analog_in_type_b__sample_group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analog_in_type_b__stream_data__field_indices_by_name[] = {
  0,   /* field[0] = samples */
};
static const ProtobufCIntRange analog_in_type_b__stream_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analog_in_type_b__stream_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analogInTypeB.StreamData",
  "StreamData",
  "AnalogInTypeB__StreamData",
  "analogInTypeB",
  sizeof(AnalogInTypeB__StreamData),
  1,
  analog_in_type_b__stream_data__field_descriptors,
  analog_in_type_b__stream_data__field_indices_by_name,
  1,  analog_in_type_b__stream_data__number_ranges,
  (ProtobufCMessageInit) analog_in_type_b__stream_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
