/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: io4edge_inventory.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "io4edge_inventory.pb-c.h"
void   io4edge_inventory__unit__init
                     (Io4edgeInventory__Unit         *message)
{
  static const Io4edgeInventory__Unit init_value = IO4EDGE_INVENTORY__UNIT__INIT;
  *message = init_value;
}
size_t io4edge_inventory__unit__get_packed_size
                     (const Io4edgeInventory__Unit *message)
{
  assert(message->base.descriptor == &io4edge_inventory__unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t io4edge_inventory__unit__pack
                     (const Io4edgeInventory__Unit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &io4edge_inventory__unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t io4edge_inventory__unit__pack_to_buffer
                     (const Io4edgeInventory__Unit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &io4edge_inventory__unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Io4edgeInventory__Unit *
       io4edge_inventory__unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Io4edgeInventory__Unit *)
     protobuf_c_message_unpack (&io4edge_inventory__unit__descriptor,
                                allocator, len, data);
}
void   io4edge_inventory__unit__free_unpacked
                     (Io4edgeInventory__Unit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &io4edge_inventory__unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor io4edge_inventory__unit__field_descriptors[3] =
{
  {
    "root_article",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Io4edgeInventory__Unit, root_article),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "major_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Io4edgeInventory__Unit, major_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Io4edgeInventory__Unit, serial),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned io4edge_inventory__unit__field_indices_by_name[] = {
  1,   /* field[1] = major_version */
  0,   /* field[0] = root_article */
  2,   /* field[2] = serial */
};
static const ProtobufCIntRange io4edge_inventory__unit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor io4edge_inventory__unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "io4edgeInventory.Unit",
  "Unit",
  "Io4edgeInventory__Unit",
  "io4edgeInventory",
  sizeof(Io4edgeInventory__Unit),
  3,
  io4edge_inventory__unit__field_descriptors,
  io4edge_inventory__unit__field_indices_by_name,
  1,  io4edge_inventory__unit__number_ranges,
  (ProtobufCMessageInit) io4edge_inventory__unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
