/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: templateInterface.proto */

#ifndef PROTOBUF_C_templateInterface_2eproto__INCLUDED
#define PROTOBUF_C_templateInterface_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _TemplateInterface__ConfigurationSet TemplateInterface__ConfigurationSet;
typedef struct _TemplateInterface__ConfigurationSetResponse TemplateInterface__ConfigurationSetResponse;
typedef struct _TemplateInterface__ConfigurationGet TemplateInterface__ConfigurationGet;
typedef struct _TemplateInterface__ConfigurationGetResponse TemplateInterface__ConfigurationGetResponse;
typedef struct _TemplateInterface__ConfigurationDescribe TemplateInterface__ConfigurationDescribe;
typedef struct _TemplateInterface__ConfigurationDescribeResponse TemplateInterface__ConfigurationDescribeResponse;
typedef struct _TemplateInterface__ConfigurationResponse TemplateInterface__ConfigurationResponse;
typedef struct _TemplateInterface__FunctionControlGet TemplateInterface__FunctionControlGet;
typedef struct _TemplateInterface__FunctionControlSet TemplateInterface__FunctionControlSet;
typedef struct _TemplateInterface__FunctionControlGetResponse TemplateInterface__FunctionControlGetResponse;
typedef struct _TemplateInterface__FunctionControlSetResponse TemplateInterface__FunctionControlSetResponse;
typedef struct _TemplateInterface__StreamControlStart TemplateInterface__StreamControlStart;
typedef struct _TemplateInterface__Sample TemplateInterface__Sample;
typedef struct _TemplateInterface__StreamData TemplateInterface__StreamData;


/* --- enums --- */


/* --- messages --- */

/*
 * ConfigurationSet to pass to Functionblock.Configuration.functionSpecificConfigurationSet hook
 */
struct  _TemplateInterface__ConfigurationSet
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values, example
   */
  uint32_t sample_rate;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_set__descriptor) \
    , 0 }


/*
 * ConfigurationSetResponse to pass to Functionblock.Configuration.functionSpecificConfigurationSetResponse hook
 */
struct  _TemplateInterface__ConfigurationSetResponse
{
  ProtobufCMessage base;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_set_response__descriptor) \
     }


/*
 * ConfigurationGet to pass to Functionblock.Configuration.functionSpecificConfigurationGet hook
 */
struct  _TemplateInterface__ConfigurationGet
{
  ProtobufCMessage base;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_get__descriptor) \
     }


/*
 * ConfigurationGetResponse to pass to Functionblock.ConfigurationGetResponse.functionSpecificConfigurationGetResponse hook
 * Returns the current hardware configuration
 */
struct  _TemplateInterface__ConfigurationGetResponse
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values, example
   */
  uint32_t sample_rate;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_get_response__descriptor) \
    , 0 }


/*
 * ConfigurationDescribe to pass to Functionblock.Configuration.functionSpecificConfigurationDescribe hook
 */
struct  _TemplateInterface__ConfigurationDescribe
{
  ProtobufCMessage base;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_DESCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_describe__descriptor) \
     }


struct  _TemplateInterface__ConfigurationDescribeResponse
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values, example
   */
  char *ident;
};
#define TEMPLATE_INTERFACE__CONFIGURATION_DESCRIBE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_describe_response__descriptor) \
    , (char *)protobuf_c_empty_string }


typedef enum {
  TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE__NOT_SET = 0,
  TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE_GET = 1,
  TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE_SET = 2,
  TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE_DESCRIBE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE)
} TemplateInterface__ConfigurationResponse__TypeCase;

/*
 * ConfigurationResponse to pass to Functionblock.ConfigurationResponse.functionSpecificConfigurationResponse hook
 */
struct  _TemplateInterface__ConfigurationResponse
{
  ProtobufCMessage base;
  TemplateInterface__ConfigurationResponse__TypeCase type_case;
  union {
    TemplateInterface__ConfigurationGetResponse *get;
    TemplateInterface__ConfigurationSetResponse *set;
    TemplateInterface__ConfigurationDescribeResponse *describe;
  };
};
#define TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__configuration_response__descriptor) \
    , TEMPLATE_INTERFACE__CONFIGURATION_RESPONSE__TYPE__NOT_SET, {0} }


/*
 * FunctionControlGet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlGet hook
 */
struct  _TemplateInterface__FunctionControlGet
{
  ProtobufCMessage base;
};
#define TEMPLATE_INTERFACE__FUNCTION_CONTROL_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__function_control_get__descriptor) \
     }


/*
 * FunctionControlSet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlSet hook
 */
struct  _TemplateInterface__FunctionControlSet
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values
   * Example:
   */
  uint32_t value;
};
#define TEMPLATE_INTERFACE__FUNCTION_CONTROL_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__function_control_set__descriptor) \
    , 0 }


/*
 * FunctionControlGetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlGet hook
 */
struct  _TemplateInterface__FunctionControlGetResponse
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values
   */
  uint32_t value;
};
#define TEMPLATE_INTERFACE__FUNCTION_CONTROL_GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__function_control_get_response__descriptor) \
    , 0 }


/*
 * FunctionControlSetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlSet hook
 */
struct  _TemplateInterface__FunctionControlSetResponse
{
  ProtobufCMessage base;
};
#define TEMPLATE_INTERFACE__FUNCTION_CONTROL_SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__function_control_set_response__descriptor) \
     }


/*
 * ============= StreamControl ==================
 * StreamControlStart to pass to Functionblock.StreamControlStart.functionSpecificStreamControlStart hook
 */
struct  _TemplateInterface__StreamControlStart
{
  ProtobufCMessage base;
  /*
   * Put here your function specific values, example
   */
  /*
   * generate a sample when counter (value % modulo) == 0
   */
  uint32_t modulo;
};
#define TEMPLATE_INTERFACE__STREAM_CONTROL_START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__stream_control_start__descriptor) \
    , 0 }


struct  _TemplateInterface__Sample
{
  ProtobufCMessage base;
  /*
   * Timestamp for that specific channels sample. This is the time the sample was taken.
   * This timestamp is in microseconds since the start of the device and does not get synchronized with the clients time.
   */
  uint64_t timestamp;
  /*
   * Specifies the binary channel value when the input value has changed.
   */
  uint32_t value;
};
#define TEMPLATE_INTERFACE__SAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__sample__descriptor) \
    , 0, 0 }


/*
 * StreamData to pass to Functionblock.StreamData.functionSpecificStreamData hook
 */
struct  _TemplateInterface__StreamData
{
  ProtobufCMessage base;
  size_t n_samples;
  TemplateInterface__Sample **samples;
};
#define TEMPLATE_INTERFACE__STREAM_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&template_interface__stream_data__descriptor) \
    , 0,NULL }


/* TemplateInterface__ConfigurationSet methods */
void   template_interface__configuration_set__init
                     (TemplateInterface__ConfigurationSet         *message);
size_t template_interface__configuration_set__get_packed_size
                     (const TemplateInterface__ConfigurationSet   *message);
size_t template_interface__configuration_set__pack
                     (const TemplateInterface__ConfigurationSet   *message,
                      uint8_t             *out);
size_t template_interface__configuration_set__pack_to_buffer
                     (const TemplateInterface__ConfigurationSet   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationSet *
       template_interface__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_set__free_unpacked
                     (TemplateInterface__ConfigurationSet *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationSetResponse methods */
void   template_interface__configuration_set_response__init
                     (TemplateInterface__ConfigurationSetResponse         *message);
size_t template_interface__configuration_set_response__get_packed_size
                     (const TemplateInterface__ConfigurationSetResponse   *message);
size_t template_interface__configuration_set_response__pack
                     (const TemplateInterface__ConfigurationSetResponse   *message,
                      uint8_t             *out);
size_t template_interface__configuration_set_response__pack_to_buffer
                     (const TemplateInterface__ConfigurationSetResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationSetResponse *
       template_interface__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_set_response__free_unpacked
                     (TemplateInterface__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationGet methods */
void   template_interface__configuration_get__init
                     (TemplateInterface__ConfigurationGet         *message);
size_t template_interface__configuration_get__get_packed_size
                     (const TemplateInterface__ConfigurationGet   *message);
size_t template_interface__configuration_get__pack
                     (const TemplateInterface__ConfigurationGet   *message,
                      uint8_t             *out);
size_t template_interface__configuration_get__pack_to_buffer
                     (const TemplateInterface__ConfigurationGet   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationGet *
       template_interface__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_get__free_unpacked
                     (TemplateInterface__ConfigurationGet *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationGetResponse methods */
void   template_interface__configuration_get_response__init
                     (TemplateInterface__ConfigurationGetResponse         *message);
size_t template_interface__configuration_get_response__get_packed_size
                     (const TemplateInterface__ConfigurationGetResponse   *message);
size_t template_interface__configuration_get_response__pack
                     (const TemplateInterface__ConfigurationGetResponse   *message,
                      uint8_t             *out);
size_t template_interface__configuration_get_response__pack_to_buffer
                     (const TemplateInterface__ConfigurationGetResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationGetResponse *
       template_interface__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_get_response__free_unpacked
                     (TemplateInterface__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationDescribe methods */
void   template_interface__configuration_describe__init
                     (TemplateInterface__ConfigurationDescribe         *message);
size_t template_interface__configuration_describe__get_packed_size
                     (const TemplateInterface__ConfigurationDescribe   *message);
size_t template_interface__configuration_describe__pack
                     (const TemplateInterface__ConfigurationDescribe   *message,
                      uint8_t             *out);
size_t template_interface__configuration_describe__pack_to_buffer
                     (const TemplateInterface__ConfigurationDescribe   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationDescribe *
       template_interface__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_describe__free_unpacked
                     (TemplateInterface__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationDescribeResponse methods */
void   template_interface__configuration_describe_response__init
                     (TemplateInterface__ConfigurationDescribeResponse         *message);
size_t template_interface__configuration_describe_response__get_packed_size
                     (const TemplateInterface__ConfigurationDescribeResponse   *message);
size_t template_interface__configuration_describe_response__pack
                     (const TemplateInterface__ConfigurationDescribeResponse   *message,
                      uint8_t             *out);
size_t template_interface__configuration_describe_response__pack_to_buffer
                     (const TemplateInterface__ConfigurationDescribeResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationDescribeResponse *
       template_interface__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_describe_response__free_unpacked
                     (TemplateInterface__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__ConfigurationResponse methods */
void   template_interface__configuration_response__init
                     (TemplateInterface__ConfigurationResponse         *message);
size_t template_interface__configuration_response__get_packed_size
                     (const TemplateInterface__ConfigurationResponse   *message);
size_t template_interface__configuration_response__pack
                     (const TemplateInterface__ConfigurationResponse   *message,
                      uint8_t             *out);
size_t template_interface__configuration_response__pack_to_buffer
                     (const TemplateInterface__ConfigurationResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__ConfigurationResponse *
       template_interface__configuration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__configuration_response__free_unpacked
                     (TemplateInterface__ConfigurationResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__FunctionControlGet methods */
void   template_interface__function_control_get__init
                     (TemplateInterface__FunctionControlGet         *message);
size_t template_interface__function_control_get__get_packed_size
                     (const TemplateInterface__FunctionControlGet   *message);
size_t template_interface__function_control_get__pack
                     (const TemplateInterface__FunctionControlGet   *message,
                      uint8_t             *out);
size_t template_interface__function_control_get__pack_to_buffer
                     (const TemplateInterface__FunctionControlGet   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__FunctionControlGet *
       template_interface__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__function_control_get__free_unpacked
                     (TemplateInterface__FunctionControlGet *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__FunctionControlSet methods */
void   template_interface__function_control_set__init
                     (TemplateInterface__FunctionControlSet         *message);
size_t template_interface__function_control_set__get_packed_size
                     (const TemplateInterface__FunctionControlSet   *message);
size_t template_interface__function_control_set__pack
                     (const TemplateInterface__FunctionControlSet   *message,
                      uint8_t             *out);
size_t template_interface__function_control_set__pack_to_buffer
                     (const TemplateInterface__FunctionControlSet   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__FunctionControlSet *
       template_interface__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__function_control_set__free_unpacked
                     (TemplateInterface__FunctionControlSet *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__FunctionControlGetResponse methods */
void   template_interface__function_control_get_response__init
                     (TemplateInterface__FunctionControlGetResponse         *message);
size_t template_interface__function_control_get_response__get_packed_size
                     (const TemplateInterface__FunctionControlGetResponse   *message);
size_t template_interface__function_control_get_response__pack
                     (const TemplateInterface__FunctionControlGetResponse   *message,
                      uint8_t             *out);
size_t template_interface__function_control_get_response__pack_to_buffer
                     (const TemplateInterface__FunctionControlGetResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__FunctionControlGetResponse *
       template_interface__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__function_control_get_response__free_unpacked
                     (TemplateInterface__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__FunctionControlSetResponse methods */
void   template_interface__function_control_set_response__init
                     (TemplateInterface__FunctionControlSetResponse         *message);
size_t template_interface__function_control_set_response__get_packed_size
                     (const TemplateInterface__FunctionControlSetResponse   *message);
size_t template_interface__function_control_set_response__pack
                     (const TemplateInterface__FunctionControlSetResponse   *message,
                      uint8_t             *out);
size_t template_interface__function_control_set_response__pack_to_buffer
                     (const TemplateInterface__FunctionControlSetResponse   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__FunctionControlSetResponse *
       template_interface__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__function_control_set_response__free_unpacked
                     (TemplateInterface__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__StreamControlStart methods */
void   template_interface__stream_control_start__init
                     (TemplateInterface__StreamControlStart         *message);
size_t template_interface__stream_control_start__get_packed_size
                     (const TemplateInterface__StreamControlStart   *message);
size_t template_interface__stream_control_start__pack
                     (const TemplateInterface__StreamControlStart   *message,
                      uint8_t             *out);
size_t template_interface__stream_control_start__pack_to_buffer
                     (const TemplateInterface__StreamControlStart   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__StreamControlStart *
       template_interface__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__stream_control_start__free_unpacked
                     (TemplateInterface__StreamControlStart *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__Sample methods */
void   template_interface__sample__init
                     (TemplateInterface__Sample         *message);
size_t template_interface__sample__get_packed_size
                     (const TemplateInterface__Sample   *message);
size_t template_interface__sample__pack
                     (const TemplateInterface__Sample   *message,
                      uint8_t             *out);
size_t template_interface__sample__pack_to_buffer
                     (const TemplateInterface__Sample   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__Sample *
       template_interface__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__sample__free_unpacked
                     (TemplateInterface__Sample *message,
                      ProtobufCAllocator *allocator);
/* TemplateInterface__StreamData methods */
void   template_interface__stream_data__init
                     (TemplateInterface__StreamData         *message);
size_t template_interface__stream_data__get_packed_size
                     (const TemplateInterface__StreamData   *message);
size_t template_interface__stream_data__pack
                     (const TemplateInterface__StreamData   *message,
                      uint8_t             *out);
size_t template_interface__stream_data__pack_to_buffer
                     (const TemplateInterface__StreamData   *message,
                      ProtobufCBuffer     *buffer);
TemplateInterface__StreamData *
       template_interface__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   template_interface__stream_data__free_unpacked
                     (TemplateInterface__StreamData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TemplateInterface__ConfigurationSet_Closure)
                 (const TemplateInterface__ConfigurationSet *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationSetResponse_Closure)
                 (const TemplateInterface__ConfigurationSetResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationGet_Closure)
                 (const TemplateInterface__ConfigurationGet *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationGetResponse_Closure)
                 (const TemplateInterface__ConfigurationGetResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationDescribe_Closure)
                 (const TemplateInterface__ConfigurationDescribe *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationDescribeResponse_Closure)
                 (const TemplateInterface__ConfigurationDescribeResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__ConfigurationResponse_Closure)
                 (const TemplateInterface__ConfigurationResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__FunctionControlGet_Closure)
                 (const TemplateInterface__FunctionControlGet *message,
                  void *closure_data);
typedef void (*TemplateInterface__FunctionControlSet_Closure)
                 (const TemplateInterface__FunctionControlSet *message,
                  void *closure_data);
typedef void (*TemplateInterface__FunctionControlGetResponse_Closure)
                 (const TemplateInterface__FunctionControlGetResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__FunctionControlSetResponse_Closure)
                 (const TemplateInterface__FunctionControlSetResponse *message,
                  void *closure_data);
typedef void (*TemplateInterface__StreamControlStart_Closure)
                 (const TemplateInterface__StreamControlStart *message,
                  void *closure_data);
typedef void (*TemplateInterface__Sample_Closure)
                 (const TemplateInterface__Sample *message,
                  void *closure_data);
typedef void (*TemplateInterface__StreamData_Closure)
                 (const TemplateInterface__StreamData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor template_interface__configuration_set__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_set_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_get__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_get_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_describe__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_describe_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__configuration_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__function_control_get__descriptor;
extern const ProtobufCMessageDescriptor template_interface__function_control_set__descriptor;
extern const ProtobufCMessageDescriptor template_interface__function_control_get_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__function_control_set_response__descriptor;
extern const ProtobufCMessageDescriptor template_interface__stream_control_start__descriptor;
extern const ProtobufCMessageDescriptor template_interface__sample__descriptor;
extern const ProtobufCMessageDescriptor template_interface__stream_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_templateInterface_2eproto__INCLUDED */
