/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bitbusSlave.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bitbusSlave.pb-c.h"
void   bitbus_slave__configuration_set__init
                     (BitbusSlave__ConfigurationSet         *message)
{
  static const BitbusSlave__ConfigurationSet init_value = BITBUS_SLAVE__CONFIGURATION_SET__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_set__get_packed_size
                     (const BitbusSlave__ConfigurationSet *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_set__pack
                     (const BitbusSlave__ConfigurationSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_set__pack_to_buffer
                     (const BitbusSlave__ConfigurationSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationSet *
       bitbus_slave__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationSet *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_set__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_set__free_unpacked
                     (BitbusSlave__ConfigurationSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__configuration_set_response__init
                     (BitbusSlave__ConfigurationSetResponse         *message)
{
  static const BitbusSlave__ConfigurationSetResponse init_value = BITBUS_SLAVE__CONFIGURATION_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_set_response__get_packed_size
                     (const BitbusSlave__ConfigurationSetResponse *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_set_response__pack
                     (const BitbusSlave__ConfigurationSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_set_response__pack_to_buffer
                     (const BitbusSlave__ConfigurationSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationSetResponse *
       bitbus_slave__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationSetResponse *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_set_response__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_set_response__free_unpacked
                     (BitbusSlave__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__configuration_get__init
                     (BitbusSlave__ConfigurationGet         *message)
{
  static const BitbusSlave__ConfigurationGet init_value = BITBUS_SLAVE__CONFIGURATION_GET__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_get__get_packed_size
                     (const BitbusSlave__ConfigurationGet *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_get__pack
                     (const BitbusSlave__ConfigurationGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_get__pack_to_buffer
                     (const BitbusSlave__ConfigurationGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationGet *
       bitbus_slave__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationGet *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_get__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_get__free_unpacked
                     (BitbusSlave__ConfigurationGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__configuration_get_response__init
                     (BitbusSlave__ConfigurationGetResponse         *message)
{
  static const BitbusSlave__ConfigurationGetResponse init_value = BITBUS_SLAVE__CONFIGURATION_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_get_response__get_packed_size
                     (const BitbusSlave__ConfigurationGetResponse *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_get_response__pack
                     (const BitbusSlave__ConfigurationGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_get_response__pack_to_buffer
                     (const BitbusSlave__ConfigurationGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationGetResponse *
       bitbus_slave__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationGetResponse *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_get_response__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_get_response__free_unpacked
                     (BitbusSlave__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__configuration_describe__init
                     (BitbusSlave__ConfigurationDescribe         *message)
{
  static const BitbusSlave__ConfigurationDescribe init_value = BITBUS_SLAVE__CONFIGURATION_DESCRIBE__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_describe__get_packed_size
                     (const BitbusSlave__ConfigurationDescribe *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_describe__pack
                     (const BitbusSlave__ConfigurationDescribe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_describe__pack_to_buffer
                     (const BitbusSlave__ConfigurationDescribe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationDescribe *
       bitbus_slave__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationDescribe *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_describe__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_describe__free_unpacked
                     (BitbusSlave__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_describe__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__configuration_describe_response__init
                     (BitbusSlave__ConfigurationDescribeResponse         *message)
{
  static const BitbusSlave__ConfigurationDescribeResponse init_value = BITBUS_SLAVE__CONFIGURATION_DESCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t bitbus_slave__configuration_describe_response__get_packed_size
                     (const BitbusSlave__ConfigurationDescribeResponse *message)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__configuration_describe_response__pack
                     (const BitbusSlave__ConfigurationDescribeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__configuration_describe_response__pack_to_buffer
                     (const BitbusSlave__ConfigurationDescribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__configuration_describe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__ConfigurationDescribeResponse *
       bitbus_slave__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__ConfigurationDescribeResponse *)
     protobuf_c_message_unpack (&bitbus_slave__configuration_describe_response__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__configuration_describe_response__free_unpacked
                     (BitbusSlave__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__configuration_describe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__function_control_get__init
                     (BitbusSlave__FunctionControlGet         *message)
{
  static const BitbusSlave__FunctionControlGet init_value = BITBUS_SLAVE__FUNCTION_CONTROL_GET__INIT;
  *message = init_value;
}
size_t bitbus_slave__function_control_get__get_packed_size
                     (const BitbusSlave__FunctionControlGet *message)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__function_control_get__pack
                     (const BitbusSlave__FunctionControlGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__function_control_get__pack_to_buffer
                     (const BitbusSlave__FunctionControlGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__FunctionControlGet *
       bitbus_slave__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__FunctionControlGet *)
     protobuf_c_message_unpack (&bitbus_slave__function_control_get__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__function_control_get__free_unpacked
                     (BitbusSlave__FunctionControlGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__function_control_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__prepared_tx_msg__init
                     (BitbusSlave__PreparedTxMsg         *message)
{
  static const BitbusSlave__PreparedTxMsg init_value = BITBUS_SLAVE__PREPARED_TX_MSG__INIT;
  *message = init_value;
}
size_t bitbus_slave__prepared_tx_msg__get_packed_size
                     (const BitbusSlave__PreparedTxMsg *message)
{
  assert(message->base.descriptor == &bitbus_slave__prepared_tx_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__prepared_tx_msg__pack
                     (const BitbusSlave__PreparedTxMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__prepared_tx_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__prepared_tx_msg__pack_to_buffer
                     (const BitbusSlave__PreparedTxMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__prepared_tx_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__PreparedTxMsg *
       bitbus_slave__prepared_tx_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__PreparedTxMsg *)
     protobuf_c_message_unpack (&bitbus_slave__prepared_tx_msg__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__prepared_tx_msg__free_unpacked
                     (BitbusSlave__PreparedTxMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__prepared_tx_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__function_control_set__init
                     (BitbusSlave__FunctionControlSet         *message)
{
  static const BitbusSlave__FunctionControlSet init_value = BITBUS_SLAVE__FUNCTION_CONTROL_SET__INIT;
  *message = init_value;
}
size_t bitbus_slave__function_control_set__get_packed_size
                     (const BitbusSlave__FunctionControlSet *message)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__function_control_set__pack
                     (const BitbusSlave__FunctionControlSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__function_control_set__pack_to_buffer
                     (const BitbusSlave__FunctionControlSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__FunctionControlSet *
       bitbus_slave__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__FunctionControlSet *)
     protobuf_c_message_unpack (&bitbus_slave__function_control_set__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__function_control_set__free_unpacked
                     (BitbusSlave__FunctionControlSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__function_control_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__function_control_get_response__init
                     (BitbusSlave__FunctionControlGetResponse         *message)
{
  static const BitbusSlave__FunctionControlGetResponse init_value = BITBUS_SLAVE__FUNCTION_CONTROL_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t bitbus_slave__function_control_get_response__get_packed_size
                     (const BitbusSlave__FunctionControlGetResponse *message)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__function_control_get_response__pack
                     (const BitbusSlave__FunctionControlGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__function_control_get_response__pack_to_buffer
                     (const BitbusSlave__FunctionControlGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__FunctionControlGetResponse *
       bitbus_slave__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__FunctionControlGetResponse *)
     protobuf_c_message_unpack (&bitbus_slave__function_control_get_response__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__function_control_get_response__free_unpacked
                     (BitbusSlave__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__function_control_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__function_control_set_response__init
                     (BitbusSlave__FunctionControlSetResponse         *message)
{
  static const BitbusSlave__FunctionControlSetResponse init_value = BITBUS_SLAVE__FUNCTION_CONTROL_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t bitbus_slave__function_control_set_response__get_packed_size
                     (const BitbusSlave__FunctionControlSetResponse *message)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__function_control_set_response__pack
                     (const BitbusSlave__FunctionControlSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__function_control_set_response__pack_to_buffer
                     (const BitbusSlave__FunctionControlSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__function_control_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__FunctionControlSetResponse *
       bitbus_slave__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__FunctionControlSetResponse *)
     protobuf_c_message_unpack (&bitbus_slave__function_control_set_response__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__function_control_set_response__free_unpacked
                     (BitbusSlave__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__function_control_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__stream_control_start__init
                     (BitbusSlave__StreamControlStart         *message)
{
  static const BitbusSlave__StreamControlStart init_value = BITBUS_SLAVE__STREAM_CONTROL_START__INIT;
  *message = init_value;
}
size_t bitbus_slave__stream_control_start__get_packed_size
                     (const BitbusSlave__StreamControlStart *message)
{
  assert(message->base.descriptor == &bitbus_slave__stream_control_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__stream_control_start__pack
                     (const BitbusSlave__StreamControlStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__stream_control_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__stream_control_start__pack_to_buffer
                     (const BitbusSlave__StreamControlStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__stream_control_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__StreamControlStart *
       bitbus_slave__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__StreamControlStart *)
     protobuf_c_message_unpack (&bitbus_slave__stream_control_start__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__stream_control_start__free_unpacked
                     (BitbusSlave__StreamControlStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__stream_control_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__sample__init
                     (BitbusSlave__Sample         *message)
{
  static const BitbusSlave__Sample init_value = BITBUS_SLAVE__SAMPLE__INIT;
  *message = init_value;
}
size_t bitbus_slave__sample__get_packed_size
                     (const BitbusSlave__Sample *message)
{
  assert(message->base.descriptor == &bitbus_slave__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__sample__pack
                     (const BitbusSlave__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__sample__pack_to_buffer
                     (const BitbusSlave__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__Sample *
       bitbus_slave__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__Sample *)
     protobuf_c_message_unpack (&bitbus_slave__sample__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__sample__free_unpacked
                     (BitbusSlave__Sample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitbus_slave__stream_data__init
                     (BitbusSlave__StreamData         *message)
{
  static const BitbusSlave__StreamData init_value = BITBUS_SLAVE__STREAM_DATA__INIT;
  *message = init_value;
}
size_t bitbus_slave__stream_data__get_packed_size
                     (const BitbusSlave__StreamData *message)
{
  assert(message->base.descriptor == &bitbus_slave__stream_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitbus_slave__stream_data__pack
                     (const BitbusSlave__StreamData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitbus_slave__stream_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitbus_slave__stream_data__pack_to_buffer
                     (const BitbusSlave__StreamData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitbus_slave__stream_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BitbusSlave__StreamData *
       bitbus_slave__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BitbusSlave__StreamData *)
     protobuf_c_message_unpack (&bitbus_slave__stream_data__descriptor,
                                allocator, len, data);
}
void   bitbus_slave__stream_data__free_unpacked
                     (BitbusSlave__StreamData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitbus_slave__stream_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bitbus_slave__configuration_set__field_descriptors[5] =
{
  {
    "slave_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__ConfigurationSet, slave_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_frame_length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__ConfigurationSet, max_frame_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_wd_timeout_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__ConfigurationSet, app_wd_timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idle_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__ConfigurationSet, idle_response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_62500",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__ConfigurationSet, baud_62500),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__configuration_set__field_indices_by_name[] = {
  2,   /* field[2] = app_wd_timeout_ms */
  4,   /* field[4] = baud_62500 */
  3,   /* field[3] = idle_response */
  1,   /* field[1] = max_frame_length */
  0,   /* field[0] = slave_address */
};
static const ProtobufCIntRange bitbus_slave__configuration_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor bitbus_slave__configuration_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationSet",
  "ConfigurationSet",
  "BitbusSlave__ConfigurationSet",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationSet),
  5,
  bitbus_slave__configuration_set__field_descriptors,
  bitbus_slave__configuration_set__field_indices_by_name,
  1,  bitbus_slave__configuration_set__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__configuration_set_response__field_descriptors NULL
#define bitbus_slave__configuration_set_response__field_indices_by_name NULL
#define bitbus_slave__configuration_set_response__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__configuration_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationSetResponse",
  "ConfigurationSetResponse",
  "BitbusSlave__ConfigurationSetResponse",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationSetResponse),
  0,
  bitbus_slave__configuration_set_response__field_descriptors,
  bitbus_slave__configuration_set_response__field_indices_by_name,
  0,  bitbus_slave__configuration_set_response__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__configuration_get__field_descriptors NULL
#define bitbus_slave__configuration_get__field_indices_by_name NULL
#define bitbus_slave__configuration_get__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__configuration_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationGet",
  "ConfigurationGet",
  "BitbusSlave__ConfigurationGet",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationGet),
  0,
  bitbus_slave__configuration_get__field_descriptors,
  bitbus_slave__configuration_get__field_indices_by_name,
  0,  bitbus_slave__configuration_get__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__configuration_get_response__field_descriptors NULL
#define bitbus_slave__configuration_get_response__field_indices_by_name NULL
#define bitbus_slave__configuration_get_response__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__configuration_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationGetResponse",
  "ConfigurationGetResponse",
  "BitbusSlave__ConfigurationGetResponse",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationGetResponse),
  0,
  bitbus_slave__configuration_get_response__field_descriptors,
  bitbus_slave__configuration_get_response__field_indices_by_name,
  0,  bitbus_slave__configuration_get_response__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__configuration_describe__field_descriptors NULL
#define bitbus_slave__configuration_describe__field_indices_by_name NULL
#define bitbus_slave__configuration_describe__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__configuration_describe__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationDescribe",
  "ConfigurationDescribe",
  "BitbusSlave__ConfigurationDescribe",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationDescribe),
  0,
  bitbus_slave__configuration_describe__field_descriptors,
  bitbus_slave__configuration_describe__field_indices_by_name,
  0,  bitbus_slave__configuration_describe__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_describe__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__configuration_describe_response__field_descriptors NULL
#define bitbus_slave__configuration_describe_response__field_indices_by_name NULL
#define bitbus_slave__configuration_describe_response__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__configuration_describe_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.ConfigurationDescribeResponse",
  "ConfigurationDescribeResponse",
  "BitbusSlave__ConfigurationDescribeResponse",
  "bitbusSlave",
  sizeof(BitbusSlave__ConfigurationDescribeResponse),
  0,
  bitbus_slave__configuration_describe_response__field_descriptors,
  bitbus_slave__configuration_describe_response__field_indices_by_name,
  0,  bitbus_slave__configuration_describe_response__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__configuration_describe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__function_control_get__field_descriptors NULL
#define bitbus_slave__function_control_get__field_indices_by_name NULL
#define bitbus_slave__function_control_get__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__function_control_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.FunctionControlGet",
  "FunctionControlGet",
  "BitbusSlave__FunctionControlGet",
  "bitbusSlave",
  sizeof(BitbusSlave__FunctionControlGet),
  0,
  bitbus_slave__function_control_get__field_descriptors,
  bitbus_slave__function_control_get__field_indices_by_name,
  0,  bitbus_slave__function_control_get__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__function_control_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitbus_slave__prepared_tx_msg__field_descriptors[1] =
{
  {
    "bitbus_information",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__PreparedTxMsg, bitbus_information),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__prepared_tx_msg__field_indices_by_name[] = {
  0,   /* field[0] = bitbus_information */
};
static const ProtobufCIntRange bitbus_slave__prepared_tx_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bitbus_slave__prepared_tx_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.PreparedTxMsg",
  "PreparedTxMsg",
  "BitbusSlave__PreparedTxMsg",
  "bitbusSlave",
  sizeof(BitbusSlave__PreparedTxMsg),
  1,
  bitbus_slave__prepared_tx_msg__field_descriptors,
  bitbus_slave__prepared_tx_msg__field_indices_by_name,
  1,  bitbus_slave__prepared_tx_msg__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__prepared_tx_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitbus_slave__function_control_set__field_descriptors[1] =
{
  {
    "tx_msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BitbusSlave__FunctionControlSet, type_case),
    offsetof(BitbusSlave__FunctionControlSet, tx_msg),
    &bitbus_slave__prepared_tx_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__function_control_set__field_indices_by_name[] = {
  0,   /* field[0] = tx_msg */
};
static const ProtobufCIntRange bitbus_slave__function_control_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bitbus_slave__function_control_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.FunctionControlSet",
  "FunctionControlSet",
  "BitbusSlave__FunctionControlSet",
  "bitbusSlave",
  sizeof(BitbusSlave__FunctionControlSet),
  1,
  bitbus_slave__function_control_set__field_descriptors,
  bitbus_slave__function_control_set__field_indices_by_name,
  1,  bitbus_slave__function_control_set__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__function_control_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__function_control_get_response__field_descriptors NULL
#define bitbus_slave__function_control_get_response__field_indices_by_name NULL
#define bitbus_slave__function_control_get_response__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__function_control_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.FunctionControlGetResponse",
  "FunctionControlGetResponse",
  "BitbusSlave__FunctionControlGetResponse",
  "bitbusSlave",
  sizeof(BitbusSlave__FunctionControlGetResponse),
  0,
  bitbus_slave__function_control_get_response__field_descriptors,
  bitbus_slave__function_control_get_response__field_indices_by_name,
  0,  bitbus_slave__function_control_get_response__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__function_control_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitbus_slave__function_control_set_response__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__FunctionControlSetResponse, mode),
    &bitbus_slave__slave_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "have_pending_tx_msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__FunctionControlSetResponse, have_pending_tx_msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__function_control_set_response__field_indices_by_name[] = {
  1,   /* field[1] = have_pending_tx_msg */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange bitbus_slave__function_control_set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bitbus_slave__function_control_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.FunctionControlSetResponse",
  "FunctionControlSetResponse",
  "BitbusSlave__FunctionControlSetResponse",
  "bitbusSlave",
  sizeof(BitbusSlave__FunctionControlSetResponse),
  2,
  bitbus_slave__function_control_set_response__field_descriptors,
  bitbus_slave__function_control_set_response__field_indices_by_name,
  1,  bitbus_slave__function_control_set_response__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__function_control_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define bitbus_slave__stream_control_start__field_descriptors NULL
#define bitbus_slave__stream_control_start__field_indices_by_name NULL
#define bitbus_slave__stream_control_start__number_ranges NULL
const ProtobufCMessageDescriptor bitbus_slave__stream_control_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.StreamControlStart",
  "StreamControlStart",
  "BitbusSlave__StreamControlStart",
  "bitbusSlave",
  sizeof(BitbusSlave__StreamControlStart),
  0,
  bitbus_slave__stream_control_start__field_descriptors,
  bitbus_slave__stream_control_start__field_indices_by_name,
  0,  bitbus_slave__stream_control_start__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__stream_control_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitbus_slave__sample__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__Sample, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitbus_information",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BitbusSlave__Sample, bitbus_information),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__sample__field_indices_by_name[] = {
  1,   /* field[1] = bitbus_information */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange bitbus_slave__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bitbus_slave__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.Sample",
  "Sample",
  "BitbusSlave__Sample",
  "bitbusSlave",
  sizeof(BitbusSlave__Sample),
  2,
  bitbus_slave__sample__field_descriptors,
  bitbus_slave__sample__field_indices_by_name,
  1,  bitbus_slave__sample__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitbus_slave__stream_data__field_descriptors[1] =
{
  {
    "samples",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BitbusSlave__StreamData, n_samples),
    offsetof(BitbusSlave__StreamData, samples),
    &bitbus_slave__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitbus_slave__stream_data__field_indices_by_name[] = {
  0,   /* field[0] = samples */
};
static const ProtobufCIntRange bitbus_slave__stream_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bitbus_slave__stream_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bitbusSlave.StreamData",
  "StreamData",
  "BitbusSlave__StreamData",
  "bitbusSlave",
  sizeof(BitbusSlave__StreamData),
  1,
  bitbus_slave__stream_data__field_descriptors,
  bitbus_slave__stream_data__field_indices_by_name,
  1,  bitbus_slave__stream_data__number_ranges,
  (ProtobufCMessageInit) bitbus_slave__stream_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue bitbus_slave__slave_mode__enum_values_by_number[3] =
{
  { "not_configured", "BITBUS_SLAVE__SLAVE_MODE__not_configured", 0 },
  { "ndm", "BITBUS_SLAVE__SLAVE_MODE__ndm", 1 },
  { "nrm", "BITBUS_SLAVE__SLAVE_MODE__nrm", 2 },
};
static const ProtobufCIntRange bitbus_slave__slave_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex bitbus_slave__slave_mode__enum_values_by_name[3] =
{
  { "ndm", 1 },
  { "not_configured", 0 },
  { "nrm", 2 },
};
const ProtobufCEnumDescriptor bitbus_slave__slave_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bitbusSlave.SlaveMode",
  "SlaveMode",
  "BitbusSlave__SlaveMode",
  "bitbusSlave",
  3,
  bitbus_slave__slave_mode__enum_values_by_number,
  3,
  bitbus_slave__slave_mode__enum_values_by_name,
  1,
  bitbus_slave__slave_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
