/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: motionSensor.proto */

#ifndef PROTOBUF_C_motionSensor_2eproto__INCLUDED
#define PROTOBUF_C_motionSensor_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct MotionSensor__ConfigurationSet MotionSensor__ConfigurationSet;
typedef struct MotionSensor__ConfigurationSetResponse MotionSensor__ConfigurationSetResponse;
typedef struct MotionSensor__ConfigurationGet MotionSensor__ConfigurationGet;
typedef struct MotionSensor__ConfigurationGetResponse MotionSensor__ConfigurationGetResponse;
typedef struct MotionSensor__ConfigurationDescribe MotionSensor__ConfigurationDescribe;
typedef struct MotionSensor__ConfigurationDescribeResponse MotionSensor__ConfigurationDescribeResponse;
typedef struct MotionSensor__FunctionControlGet MotionSensor__FunctionControlGet;
typedef struct MotionSensor__FunctionControlSet MotionSensor__FunctionControlSet;
typedef struct MotionSensor__FunctionControlGetResponse MotionSensor__FunctionControlGetResponse;
typedef struct MotionSensor__FunctionControlSetResponse MotionSensor__FunctionControlSetResponse;
typedef struct MotionSensor__StreamControlStart MotionSensor__StreamControlStart;
typedef struct MotionSensor__Sample MotionSensor__Sample;
typedef struct MotionSensor__StreamData MotionSensor__StreamData;


/* --- enums --- */


/* --- messages --- */

/*
 * ConfigurationSet to pass to Functionblock.Configuration.functionSpecificConfigurationSet hook
 */
struct  MotionSensor__ConfigurationSet
{
  ProtobufCMessage base;
  /*
   * Desired data rate in 1/1000 Hz
   */
  uint32_t sample_rate_millihz;
  /*
   * Full scale acceleration in g
   */
  int32_t full_scale_g;
  /*
   * Whether to enable high-pass filter (i.e. don't use low pass)
   */
  protobuf_c_boolean high_pass_filter_enable;
  /*
   * band width of low/hig-hpass as ratio of sample_rate
   * .e.g. select 2 when the filterbandwith shall be sample_rate/2
   */
  int32_t band_width_ratio;
};
#define MOTION_SENSOR__CONFIGURATION_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_set__descriptor) \
    , 0, 0, 0, 0 }


/*
 * ConfigurationSetResponse to pass to Functionblock.Configuration.functionSpecificConfigurationSetResponse hook
 */
struct  MotionSensor__ConfigurationSetResponse
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__CONFIGURATION_SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_set_response__descriptor) \
     }


/*
 * ConfigurationGet to pass to Functionblock.Configuration.functionSpecificConfigurationGet hook
 */
struct  MotionSensor__ConfigurationGet
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__CONFIGURATION_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_get__descriptor) \
     }


/*
 * ConfigurationGetResponse to pass to Functionblock.ConfigurationGetResponse.functionSpecificConfigurationGetResponse hook
 * Returns the current hardware configuration
 */
struct  MotionSensor__ConfigurationGetResponse
{
  ProtobufCMessage base;
  /*
   * Actual sample rate in 1/100 Hz
   */
  uint32_t sample_rate_millihz;
  /*
   * Actual full scale acceleration in g
   */
  int32_t full_scale_g;
  /*
   * Whether high-pass filter is enabled
   */
  protobuf_c_boolean high_pass_filter_enable;
  /*
   * Actual band width of low/high-pass as ratio of sample_rate
   */
  int32_t band_width_ratio;
};
#define MOTION_SENSOR__CONFIGURATION_GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_get_response__descriptor) \
    , 0, 0, 0, 0 }


/*
 * ConfigurationDescribe to pass to Functionblock.Configuration.functionSpecificConfigurationDescribe hook
 */
struct  MotionSensor__ConfigurationDescribe
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__CONFIGURATION_DESCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_describe__descriptor) \
     }


struct  MotionSensor__ConfigurationDescribeResponse
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__CONFIGURATION_DESCRIBE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__configuration_describe_response__descriptor) \
     }


/*
 * FunctionControlGet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlGet hook
 */
struct  MotionSensor__FunctionControlGet
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__FUNCTION_CONTROL_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__function_control_get__descriptor) \
     }


/*
 * FunctionControlSet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlSet hook
 */
struct  MotionSensor__FunctionControlSet
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__FUNCTION_CONTROL_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__function_control_set__descriptor) \
     }


/*
 * FunctionControlGetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlGet hook
 */
struct  MotionSensor__FunctionControlGetResponse
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__FUNCTION_CONTROL_GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__function_control_get_response__descriptor) \
     }


/*
 * FunctionControlSetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlSet hook
 */
struct  MotionSensor__FunctionControlSetResponse
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__FUNCTION_CONTROL_SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__function_control_set_response__descriptor) \
     }


/*
 * ============= StreamControl ==================
 * StreamControlStart to pass to Functionblock.StreamControlStart.functionSpecificStreamControlStart hook
 */
struct  MotionSensor__StreamControlStart
{
  ProtobufCMessage base;
};
#define MOTION_SENSOR__STREAM_CONTROL_START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__stream_control_start__descriptor) \
     }


struct  MotionSensor__Sample
{
  ProtobufCMessage base;
  /*
   * Timestamp for that specific sample. This is the time the sample was taken.
   * This timestamp is in microseconds since the start of the device and does not get synchronized with the clients time.
   */
  uint64_t timestamp;
  /*
   * x Acceleration in g
   */
  float x;
  /*
   * y Acceleration in g
   */
  float y;
  /*
   * z Acceleration in g
   */
  float z;
};
#define MOTION_SENSOR__SAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__sample__descriptor) \
    , 0, 0, 0, 0 }


/*
 * StreamData to pass to Functionblock.StreamData.functionSpecificStreamData hook
 */
struct  MotionSensor__StreamData
{
  ProtobufCMessage base;
  size_t n_samples;
  MotionSensor__Sample **samples;
};
#define MOTION_SENSOR__STREAM_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_sensor__stream_data__descriptor) \
    , 0,NULL }


/* MotionSensor__ConfigurationSet methods */
void   motion_sensor__configuration_set__init
                     (MotionSensor__ConfigurationSet         *message);
size_t motion_sensor__configuration_set__get_packed_size
                     (const MotionSensor__ConfigurationSet   *message);
size_t motion_sensor__configuration_set__pack
                     (const MotionSensor__ConfigurationSet   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_set__pack_to_buffer
                     (const MotionSensor__ConfigurationSet   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationSet *
       motion_sensor__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_set__free_unpacked
                     (MotionSensor__ConfigurationSet *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__ConfigurationSetResponse methods */
void   motion_sensor__configuration_set_response__init
                     (MotionSensor__ConfigurationSetResponse         *message);
size_t motion_sensor__configuration_set_response__get_packed_size
                     (const MotionSensor__ConfigurationSetResponse   *message);
size_t motion_sensor__configuration_set_response__pack
                     (const MotionSensor__ConfigurationSetResponse   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_set_response__pack_to_buffer
                     (const MotionSensor__ConfigurationSetResponse   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationSetResponse *
       motion_sensor__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_set_response__free_unpacked
                     (MotionSensor__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__ConfigurationGet methods */
void   motion_sensor__configuration_get__init
                     (MotionSensor__ConfigurationGet         *message);
size_t motion_sensor__configuration_get__get_packed_size
                     (const MotionSensor__ConfigurationGet   *message);
size_t motion_sensor__configuration_get__pack
                     (const MotionSensor__ConfigurationGet   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_get__pack_to_buffer
                     (const MotionSensor__ConfigurationGet   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationGet *
       motion_sensor__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_get__free_unpacked
                     (MotionSensor__ConfigurationGet *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__ConfigurationGetResponse methods */
void   motion_sensor__configuration_get_response__init
                     (MotionSensor__ConfigurationGetResponse         *message);
size_t motion_sensor__configuration_get_response__get_packed_size
                     (const MotionSensor__ConfigurationGetResponse   *message);
size_t motion_sensor__configuration_get_response__pack
                     (const MotionSensor__ConfigurationGetResponse   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_get_response__pack_to_buffer
                     (const MotionSensor__ConfigurationGetResponse   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationGetResponse *
       motion_sensor__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_get_response__free_unpacked
                     (MotionSensor__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__ConfigurationDescribe methods */
void   motion_sensor__configuration_describe__init
                     (MotionSensor__ConfigurationDescribe         *message);
size_t motion_sensor__configuration_describe__get_packed_size
                     (const MotionSensor__ConfigurationDescribe   *message);
size_t motion_sensor__configuration_describe__pack
                     (const MotionSensor__ConfigurationDescribe   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_describe__pack_to_buffer
                     (const MotionSensor__ConfigurationDescribe   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationDescribe *
       motion_sensor__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_describe__free_unpacked
                     (MotionSensor__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__ConfigurationDescribeResponse methods */
void   motion_sensor__configuration_describe_response__init
                     (MotionSensor__ConfigurationDescribeResponse         *message);
size_t motion_sensor__configuration_describe_response__get_packed_size
                     (const MotionSensor__ConfigurationDescribeResponse   *message);
size_t motion_sensor__configuration_describe_response__pack
                     (const MotionSensor__ConfigurationDescribeResponse   *message,
                      uint8_t             *out);
size_t motion_sensor__configuration_describe_response__pack_to_buffer
                     (const MotionSensor__ConfigurationDescribeResponse   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__ConfigurationDescribeResponse *
       motion_sensor__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__configuration_describe_response__free_unpacked
                     (MotionSensor__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__FunctionControlGet methods */
void   motion_sensor__function_control_get__init
                     (MotionSensor__FunctionControlGet         *message);
size_t motion_sensor__function_control_get__get_packed_size
                     (const MotionSensor__FunctionControlGet   *message);
size_t motion_sensor__function_control_get__pack
                     (const MotionSensor__FunctionControlGet   *message,
                      uint8_t             *out);
size_t motion_sensor__function_control_get__pack_to_buffer
                     (const MotionSensor__FunctionControlGet   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__FunctionControlGet *
       motion_sensor__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__function_control_get__free_unpacked
                     (MotionSensor__FunctionControlGet *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__FunctionControlSet methods */
void   motion_sensor__function_control_set__init
                     (MotionSensor__FunctionControlSet         *message);
size_t motion_sensor__function_control_set__get_packed_size
                     (const MotionSensor__FunctionControlSet   *message);
size_t motion_sensor__function_control_set__pack
                     (const MotionSensor__FunctionControlSet   *message,
                      uint8_t             *out);
size_t motion_sensor__function_control_set__pack_to_buffer
                     (const MotionSensor__FunctionControlSet   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__FunctionControlSet *
       motion_sensor__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__function_control_set__free_unpacked
                     (MotionSensor__FunctionControlSet *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__FunctionControlGetResponse methods */
void   motion_sensor__function_control_get_response__init
                     (MotionSensor__FunctionControlGetResponse         *message);
size_t motion_sensor__function_control_get_response__get_packed_size
                     (const MotionSensor__FunctionControlGetResponse   *message);
size_t motion_sensor__function_control_get_response__pack
                     (const MotionSensor__FunctionControlGetResponse   *message,
                      uint8_t             *out);
size_t motion_sensor__function_control_get_response__pack_to_buffer
                     (const MotionSensor__FunctionControlGetResponse   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__FunctionControlGetResponse *
       motion_sensor__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__function_control_get_response__free_unpacked
                     (MotionSensor__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__FunctionControlSetResponse methods */
void   motion_sensor__function_control_set_response__init
                     (MotionSensor__FunctionControlSetResponse         *message);
size_t motion_sensor__function_control_set_response__get_packed_size
                     (const MotionSensor__FunctionControlSetResponse   *message);
size_t motion_sensor__function_control_set_response__pack
                     (const MotionSensor__FunctionControlSetResponse   *message,
                      uint8_t             *out);
size_t motion_sensor__function_control_set_response__pack_to_buffer
                     (const MotionSensor__FunctionControlSetResponse   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__FunctionControlSetResponse *
       motion_sensor__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__function_control_set_response__free_unpacked
                     (MotionSensor__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__StreamControlStart methods */
void   motion_sensor__stream_control_start__init
                     (MotionSensor__StreamControlStart         *message);
size_t motion_sensor__stream_control_start__get_packed_size
                     (const MotionSensor__StreamControlStart   *message);
size_t motion_sensor__stream_control_start__pack
                     (const MotionSensor__StreamControlStart   *message,
                      uint8_t             *out);
size_t motion_sensor__stream_control_start__pack_to_buffer
                     (const MotionSensor__StreamControlStart   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__StreamControlStart *
       motion_sensor__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__stream_control_start__free_unpacked
                     (MotionSensor__StreamControlStart *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__Sample methods */
void   motion_sensor__sample__init
                     (MotionSensor__Sample         *message);
size_t motion_sensor__sample__get_packed_size
                     (const MotionSensor__Sample   *message);
size_t motion_sensor__sample__pack
                     (const MotionSensor__Sample   *message,
                      uint8_t             *out);
size_t motion_sensor__sample__pack_to_buffer
                     (const MotionSensor__Sample   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__Sample *
       motion_sensor__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__sample__free_unpacked
                     (MotionSensor__Sample *message,
                      ProtobufCAllocator *allocator);
/* MotionSensor__StreamData methods */
void   motion_sensor__stream_data__init
                     (MotionSensor__StreamData         *message);
size_t motion_sensor__stream_data__get_packed_size
                     (const MotionSensor__StreamData   *message);
size_t motion_sensor__stream_data__pack
                     (const MotionSensor__StreamData   *message,
                      uint8_t             *out);
size_t motion_sensor__stream_data__pack_to_buffer
                     (const MotionSensor__StreamData   *message,
                      ProtobufCBuffer     *buffer);
MotionSensor__StreamData *
       motion_sensor__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_sensor__stream_data__free_unpacked
                     (MotionSensor__StreamData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MotionSensor__ConfigurationSet_Closure)
                 (const MotionSensor__ConfigurationSet *message,
                  void *closure_data);
typedef void (*MotionSensor__ConfigurationSetResponse_Closure)
                 (const MotionSensor__ConfigurationSetResponse *message,
                  void *closure_data);
typedef void (*MotionSensor__ConfigurationGet_Closure)
                 (const MotionSensor__ConfigurationGet *message,
                  void *closure_data);
typedef void (*MotionSensor__ConfigurationGetResponse_Closure)
                 (const MotionSensor__ConfigurationGetResponse *message,
                  void *closure_data);
typedef void (*MotionSensor__ConfigurationDescribe_Closure)
                 (const MotionSensor__ConfigurationDescribe *message,
                  void *closure_data);
typedef void (*MotionSensor__ConfigurationDescribeResponse_Closure)
                 (const MotionSensor__ConfigurationDescribeResponse *message,
                  void *closure_data);
typedef void (*MotionSensor__FunctionControlGet_Closure)
                 (const MotionSensor__FunctionControlGet *message,
                  void *closure_data);
typedef void (*MotionSensor__FunctionControlSet_Closure)
                 (const MotionSensor__FunctionControlSet *message,
                  void *closure_data);
typedef void (*MotionSensor__FunctionControlGetResponse_Closure)
                 (const MotionSensor__FunctionControlGetResponse *message,
                  void *closure_data);
typedef void (*MotionSensor__FunctionControlSetResponse_Closure)
                 (const MotionSensor__FunctionControlSetResponse *message,
                  void *closure_data);
typedef void (*MotionSensor__StreamControlStart_Closure)
                 (const MotionSensor__StreamControlStart *message,
                  void *closure_data);
typedef void (*MotionSensor__Sample_Closure)
                 (const MotionSensor__Sample *message,
                  void *closure_data);
typedef void (*MotionSensor__StreamData_Closure)
                 (const MotionSensor__StreamData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor motion_sensor__configuration_set__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__configuration_set_response__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__configuration_get__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__configuration_get_response__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__configuration_describe__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__configuration_describe_response__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__function_control_get__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__function_control_set__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__function_control_get_response__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__function_control_set_response__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__stream_control_start__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__sample__descriptor;
extern const ProtobufCMessageDescriptor motion_sensor__stream_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_motionSensor_2eproto__INCLUDED */
