MODULE := google/protobuf
PROTOS := timestamp.proto any.proto
VPATH := ./proto/$(MODULE):./go/google.golang.org/protobuf/types/known/anypb:./go/google.golang.org/protobuf/types/known/timestamppb:./protobuf-c/$(MODULE):./python/$(MODULE)

include ../rules.mk
