/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: watchdog.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "watchdog.pb-c.h"
void   watchdog__configuration_set__init
                     (Watchdog__ConfigurationSet         *message)
{
  static const Watchdog__ConfigurationSet init_value = WATCHDOG__CONFIGURATION_SET__INIT;
  *message = init_value;
}
size_t watchdog__configuration_set__get_packed_size
                     (const Watchdog__ConfigurationSet *message)
{
  assert(message->base.descriptor == &watchdog__configuration_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_set__pack
                     (const Watchdog__ConfigurationSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_set__pack_to_buffer
                     (const Watchdog__ConfigurationSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationSet *
       watchdog__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationSet *)
     protobuf_c_message_unpack (&watchdog__configuration_set__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_set__free_unpacked
                     (Watchdog__ConfigurationSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_set_response__init
                     (Watchdog__ConfigurationSetResponse         *message)
{
  static const Watchdog__ConfigurationSetResponse init_value = WATCHDOG__CONFIGURATION_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__configuration_set_response__get_packed_size
                     (const Watchdog__ConfigurationSetResponse *message)
{
  assert(message->base.descriptor == &watchdog__configuration_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_set_response__pack
                     (const Watchdog__ConfigurationSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_set_response__pack_to_buffer
                     (const Watchdog__ConfigurationSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationSetResponse *
       watchdog__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationSetResponse *)
     protobuf_c_message_unpack (&watchdog__configuration_set_response__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_set_response__free_unpacked
                     (Watchdog__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_get__init
                     (Watchdog__ConfigurationGet         *message)
{
  static const Watchdog__ConfigurationGet init_value = WATCHDOG__CONFIGURATION_GET__INIT;
  *message = init_value;
}
size_t watchdog__configuration_get__get_packed_size
                     (const Watchdog__ConfigurationGet *message)
{
  assert(message->base.descriptor == &watchdog__configuration_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_get__pack
                     (const Watchdog__ConfigurationGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_get__pack_to_buffer
                     (const Watchdog__ConfigurationGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationGet *
       watchdog__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationGet *)
     protobuf_c_message_unpack (&watchdog__configuration_get__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_get__free_unpacked
                     (Watchdog__ConfigurationGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_get_response__init
                     (Watchdog__ConfigurationGetResponse         *message)
{
  static const Watchdog__ConfigurationGetResponse init_value = WATCHDOG__CONFIGURATION_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__configuration_get_response__get_packed_size
                     (const Watchdog__ConfigurationGetResponse *message)
{
  assert(message->base.descriptor == &watchdog__configuration_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_get_response__pack
                     (const Watchdog__ConfigurationGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_get_response__pack_to_buffer
                     (const Watchdog__ConfigurationGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationGetResponse *
       watchdog__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationGetResponse *)
     protobuf_c_message_unpack (&watchdog__configuration_get_response__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_get_response__free_unpacked
                     (Watchdog__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_describe__init
                     (Watchdog__ConfigurationDescribe         *message)
{
  static const Watchdog__ConfigurationDescribe init_value = WATCHDOG__CONFIGURATION_DESCRIBE__INIT;
  *message = init_value;
}
size_t watchdog__configuration_describe__get_packed_size
                     (const Watchdog__ConfigurationDescribe *message)
{
  assert(message->base.descriptor == &watchdog__configuration_describe__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_describe__pack
                     (const Watchdog__ConfigurationDescribe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_describe__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_describe__pack_to_buffer
                     (const Watchdog__ConfigurationDescribe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_describe__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationDescribe *
       watchdog__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationDescribe *)
     protobuf_c_message_unpack (&watchdog__configuration_describe__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_describe__free_unpacked
                     (Watchdog__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_describe__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_describe_response__init
                     (Watchdog__ConfigurationDescribeResponse         *message)
{
  static const Watchdog__ConfigurationDescribeResponse init_value = WATCHDOG__CONFIGURATION_DESCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__configuration_describe_response__get_packed_size
                     (const Watchdog__ConfigurationDescribeResponse *message)
{
  assert(message->base.descriptor == &watchdog__configuration_describe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_describe_response__pack
                     (const Watchdog__ConfigurationDescribeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_describe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_describe_response__pack_to_buffer
                     (const Watchdog__ConfigurationDescribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_describe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationDescribeResponse *
       watchdog__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationDescribeResponse *)
     protobuf_c_message_unpack (&watchdog__configuration_describe_response__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_describe_response__free_unpacked
                     (Watchdog__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_describe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__configuration_response__init
                     (Watchdog__ConfigurationResponse         *message)
{
  static const Watchdog__ConfigurationResponse init_value = WATCHDOG__CONFIGURATION_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__configuration_response__get_packed_size
                     (const Watchdog__ConfigurationResponse *message)
{
  assert(message->base.descriptor == &watchdog__configuration_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__configuration_response__pack
                     (const Watchdog__ConfigurationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__configuration_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__configuration_response__pack_to_buffer
                     (const Watchdog__ConfigurationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__configuration_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__ConfigurationResponse *
       watchdog__configuration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__ConfigurationResponse *)
     protobuf_c_message_unpack (&watchdog__configuration_response__descriptor,
                                allocator, len, data);
}
void   watchdog__configuration_response__free_unpacked
                     (Watchdog__ConfigurationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__configuration_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__function_control_get__init
                     (Watchdog__FunctionControlGet         *message)
{
  static const Watchdog__FunctionControlGet init_value = WATCHDOG__FUNCTION_CONTROL_GET__INIT;
  *message = init_value;
}
size_t watchdog__function_control_get__get_packed_size
                     (const Watchdog__FunctionControlGet *message)
{
  assert(message->base.descriptor == &watchdog__function_control_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__function_control_get__pack
                     (const Watchdog__FunctionControlGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__function_control_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__function_control_get__pack_to_buffer
                     (const Watchdog__FunctionControlGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__function_control_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__FunctionControlGet *
       watchdog__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__FunctionControlGet *)
     protobuf_c_message_unpack (&watchdog__function_control_get__descriptor,
                                allocator, len, data);
}
void   watchdog__function_control_get__free_unpacked
                     (Watchdog__FunctionControlGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__function_control_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__function_control_set__init
                     (Watchdog__FunctionControlSet         *message)
{
  static const Watchdog__FunctionControlSet init_value = WATCHDOG__FUNCTION_CONTROL_SET__INIT;
  *message = init_value;
}
size_t watchdog__function_control_set__get_packed_size
                     (const Watchdog__FunctionControlSet *message)
{
  assert(message->base.descriptor == &watchdog__function_control_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__function_control_set__pack
                     (const Watchdog__FunctionControlSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__function_control_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__function_control_set__pack_to_buffer
                     (const Watchdog__FunctionControlSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__function_control_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__FunctionControlSet *
       watchdog__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__FunctionControlSet *)
     protobuf_c_message_unpack (&watchdog__function_control_set__descriptor,
                                allocator, len, data);
}
void   watchdog__function_control_set__free_unpacked
                     (Watchdog__FunctionControlSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__function_control_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__function_control_get_response__init
                     (Watchdog__FunctionControlGetResponse         *message)
{
  static const Watchdog__FunctionControlGetResponse init_value = WATCHDOG__FUNCTION_CONTROL_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__function_control_get_response__get_packed_size
                     (const Watchdog__FunctionControlGetResponse *message)
{
  assert(message->base.descriptor == &watchdog__function_control_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__function_control_get_response__pack
                     (const Watchdog__FunctionControlGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__function_control_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__function_control_get_response__pack_to_buffer
                     (const Watchdog__FunctionControlGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__function_control_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__FunctionControlGetResponse *
       watchdog__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__FunctionControlGetResponse *)
     protobuf_c_message_unpack (&watchdog__function_control_get_response__descriptor,
                                allocator, len, data);
}
void   watchdog__function_control_get_response__free_unpacked
                     (Watchdog__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__function_control_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__set_pixel_area_response__init
                     (Watchdog__SetPixelAreaResponse         *message)
{
  static const Watchdog__SetPixelAreaResponse init_value = WATCHDOG__SET_PIXEL_AREA_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__set_pixel_area_response__get_packed_size
                     (const Watchdog__SetPixelAreaResponse *message)
{
  assert(message->base.descriptor == &watchdog__set_pixel_area_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__set_pixel_area_response__pack
                     (const Watchdog__SetPixelAreaResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__set_pixel_area_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__set_pixel_area_response__pack_to_buffer
                     (const Watchdog__SetPixelAreaResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__set_pixel_area_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__SetPixelAreaResponse *
       watchdog__set_pixel_area_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__SetPixelAreaResponse *)
     protobuf_c_message_unpack (&watchdog__set_pixel_area_response__descriptor,
                                allocator, len, data);
}
void   watchdog__set_pixel_area_response__free_unpacked
                     (Watchdog__SetPixelAreaResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__set_pixel_area_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__set_display_on_response__init
                     (Watchdog__SetDisplayOnResponse         *message)
{
  static const Watchdog__SetDisplayOnResponse init_value = WATCHDOG__SET_DISPLAY_ON_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__set_display_on_response__get_packed_size
                     (const Watchdog__SetDisplayOnResponse *message)
{
  assert(message->base.descriptor == &watchdog__set_display_on_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__set_display_on_response__pack
                     (const Watchdog__SetDisplayOnResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__set_display_on_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__set_display_on_response__pack_to_buffer
                     (const Watchdog__SetDisplayOnResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__set_display_on_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__SetDisplayOnResponse *
       watchdog__set_display_on_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__SetDisplayOnResponse *)
     protobuf_c_message_unpack (&watchdog__set_display_on_response__descriptor,
                                allocator, len, data);
}
void   watchdog__set_display_on_response__free_unpacked
                     (Watchdog__SetDisplayOnResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__set_display_on_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__function_control_set_response__init
                     (Watchdog__FunctionControlSetResponse         *message)
{
  static const Watchdog__FunctionControlSetResponse init_value = WATCHDOG__FUNCTION_CONTROL_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t watchdog__function_control_set_response__get_packed_size
                     (const Watchdog__FunctionControlSetResponse *message)
{
  assert(message->base.descriptor == &watchdog__function_control_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__function_control_set_response__pack
                     (const Watchdog__FunctionControlSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__function_control_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__function_control_set_response__pack_to_buffer
                     (const Watchdog__FunctionControlSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__function_control_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__FunctionControlSetResponse *
       watchdog__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__FunctionControlSetResponse *)
     protobuf_c_message_unpack (&watchdog__function_control_set_response__descriptor,
                                allocator, len, data);
}
void   watchdog__function_control_set_response__free_unpacked
                     (Watchdog__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__function_control_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__stream_control_start__init
                     (Watchdog__StreamControlStart         *message)
{
  static const Watchdog__StreamControlStart init_value = WATCHDOG__STREAM_CONTROL_START__INIT;
  *message = init_value;
}
size_t watchdog__stream_control_start__get_packed_size
                     (const Watchdog__StreamControlStart *message)
{
  assert(message->base.descriptor == &watchdog__stream_control_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__stream_control_start__pack
                     (const Watchdog__StreamControlStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__stream_control_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__stream_control_start__pack_to_buffer
                     (const Watchdog__StreamControlStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__stream_control_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__StreamControlStart *
       watchdog__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__StreamControlStart *)
     protobuf_c_message_unpack (&watchdog__stream_control_start__descriptor,
                                allocator, len, data);
}
void   watchdog__stream_control_start__free_unpacked
                     (Watchdog__StreamControlStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__stream_control_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   watchdog__stream_data__init
                     (Watchdog__StreamData         *message)
{
  static const Watchdog__StreamData init_value = WATCHDOG__STREAM_DATA__INIT;
  *message = init_value;
}
size_t watchdog__stream_data__get_packed_size
                     (const Watchdog__StreamData *message)
{
  assert(message->base.descriptor == &watchdog__stream_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t watchdog__stream_data__pack
                     (const Watchdog__StreamData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &watchdog__stream_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t watchdog__stream_data__pack_to_buffer
                     (const Watchdog__StreamData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &watchdog__stream_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Watchdog__StreamData *
       watchdog__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Watchdog__StreamData *)
     protobuf_c_message_unpack (&watchdog__stream_data__descriptor,
                                allocator, len, data);
}
void   watchdog__stream_data__free_unpacked
                     (Watchdog__StreamData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &watchdog__stream_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor watchdog__configuration_set__field_descriptors[6] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wd_reboot_threshold",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, wd_reboot_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wd_reboot_window",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, wd_reboot_window),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wd_boot_delay",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, wd_boot_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strategy",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Watchdog__ConfigurationSet, strategy),
    &watchdog__watchdog_strategy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned watchdog__configuration_set__field_indices_by_name[] = {
  0,   /* field[0] = enable */
  5,   /* field[5] = strategy */
  1,   /* field[1] = timeout_ms */
  4,   /* field[4] = wd_boot_delay */
  2,   /* field[2] = wd_reboot_threshold */
  3,   /* field[3] = wd_reboot_window */
};
static const ProtobufCIntRange watchdog__configuration_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor watchdog__configuration_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationSet",
  "ConfigurationSet",
  "Watchdog__ConfigurationSet",
  "watchdog",
  sizeof(Watchdog__ConfigurationSet),
  6,
  watchdog__configuration_set__field_descriptors,
  watchdog__configuration_set__field_indices_by_name,
  1,  watchdog__configuration_set__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__configuration_set_response__field_descriptors NULL
#define watchdog__configuration_set_response__field_indices_by_name NULL
#define watchdog__configuration_set_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__configuration_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationSetResponse",
  "ConfigurationSetResponse",
  "Watchdog__ConfigurationSetResponse",
  "watchdog",
  sizeof(Watchdog__ConfigurationSetResponse),
  0,
  watchdog__configuration_set_response__field_descriptors,
  watchdog__configuration_set_response__field_indices_by_name,
  0,  watchdog__configuration_set_response__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__configuration_get__field_descriptors NULL
#define watchdog__configuration_get__field_indices_by_name NULL
#define watchdog__configuration_get__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__configuration_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationGet",
  "ConfigurationGet",
  "Watchdog__ConfigurationGet",
  "watchdog",
  sizeof(Watchdog__ConfigurationGet),
  0,
  watchdog__configuration_get__field_descriptors,
  watchdog__configuration_get__field_indices_by_name,
  0,  watchdog__configuration_get__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__configuration_get_response__field_descriptors NULL
#define watchdog__configuration_get_response__field_indices_by_name NULL
#define watchdog__configuration_get_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__configuration_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationGetResponse",
  "ConfigurationGetResponse",
  "Watchdog__ConfigurationGetResponse",
  "watchdog",
  sizeof(Watchdog__ConfigurationGetResponse),
  0,
  watchdog__configuration_get_response__field_descriptors,
  watchdog__configuration_get_response__field_indices_by_name,
  0,  watchdog__configuration_get_response__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__configuration_describe__field_descriptors NULL
#define watchdog__configuration_describe__field_indices_by_name NULL
#define watchdog__configuration_describe__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__configuration_describe__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationDescribe",
  "ConfigurationDescribe",
  "Watchdog__ConfigurationDescribe",
  "watchdog",
  sizeof(Watchdog__ConfigurationDescribe),
  0,
  watchdog__configuration_describe__field_descriptors,
  watchdog__configuration_describe__field_indices_by_name,
  0,  watchdog__configuration_describe__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_describe__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__configuration_describe_response__field_descriptors NULL
#define watchdog__configuration_describe_response__field_indices_by_name NULL
#define watchdog__configuration_describe_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__configuration_describe_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationDescribeResponse",
  "ConfigurationDescribeResponse",
  "Watchdog__ConfigurationDescribeResponse",
  "watchdog",
  sizeof(Watchdog__ConfigurationDescribeResponse),
  0,
  watchdog__configuration_describe_response__field_descriptors,
  watchdog__configuration_describe_response__field_indices_by_name,
  0,  watchdog__configuration_describe_response__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_describe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor watchdog__configuration_response__field_descriptors[3] =
{
  {
    "get",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Watchdog__ConfigurationResponse, type_case),
    offsetof(Watchdog__ConfigurationResponse, get),
    &watchdog__configuration_get_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Watchdog__ConfigurationResponse, type_case),
    offsetof(Watchdog__ConfigurationResponse, set),
    &watchdog__configuration_set_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "describe",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Watchdog__ConfigurationResponse, type_case),
    offsetof(Watchdog__ConfigurationResponse, describe),
    &watchdog__configuration_describe_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned watchdog__configuration_response__field_indices_by_name[] = {
  2,   /* field[2] = describe */
  0,   /* field[0] = get */
  1,   /* field[1] = set */
};
static const ProtobufCIntRange watchdog__configuration_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor watchdog__configuration_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.ConfigurationResponse",
  "ConfigurationResponse",
  "Watchdog__ConfigurationResponse",
  "watchdog",
  sizeof(Watchdog__ConfigurationResponse),
  3,
  watchdog__configuration_response__field_descriptors,
  watchdog__configuration_response__field_indices_by_name,
  1,  watchdog__configuration_response__number_ranges,
  (ProtobufCMessageInit) watchdog__configuration_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__function_control_get__field_descriptors NULL
#define watchdog__function_control_get__field_indices_by_name NULL
#define watchdog__function_control_get__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__function_control_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.FunctionControlGet",
  "FunctionControlGet",
  "Watchdog__FunctionControlGet",
  "watchdog",
  sizeof(Watchdog__FunctionControlGet),
  0,
  watchdog__function_control_get__field_descriptors,
  watchdog__function_control_get__field_indices_by_name,
  0,  watchdog__function_control_get__number_ranges,
  (ProtobufCMessageInit) watchdog__function_control_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor watchdog__function_control_set__field_descriptors[1] =
{
  {
    "kick",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Watchdog__FunctionControlSet, kick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned watchdog__function_control_set__field_indices_by_name[] = {
  0,   /* field[0] = kick */
};
static const ProtobufCIntRange watchdog__function_control_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor watchdog__function_control_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.FunctionControlSet",
  "FunctionControlSet",
  "Watchdog__FunctionControlSet",
  "watchdog",
  sizeof(Watchdog__FunctionControlSet),
  1,
  watchdog__function_control_set__field_descriptors,
  watchdog__function_control_set__field_indices_by_name,
  1,  watchdog__function_control_set__number_ranges,
  (ProtobufCMessageInit) watchdog__function_control_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__function_control_get_response__field_descriptors NULL
#define watchdog__function_control_get_response__field_indices_by_name NULL
#define watchdog__function_control_get_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__function_control_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.FunctionControlGetResponse",
  "FunctionControlGetResponse",
  "Watchdog__FunctionControlGetResponse",
  "watchdog",
  sizeof(Watchdog__FunctionControlGetResponse),
  0,
  watchdog__function_control_get_response__field_descriptors,
  watchdog__function_control_get_response__field_indices_by_name,
  0,  watchdog__function_control_get_response__number_ranges,
  (ProtobufCMessageInit) watchdog__function_control_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__set_pixel_area_response__field_descriptors NULL
#define watchdog__set_pixel_area_response__field_indices_by_name NULL
#define watchdog__set_pixel_area_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__set_pixel_area_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.SetPixelAreaResponse",
  "SetPixelAreaResponse",
  "Watchdog__SetPixelAreaResponse",
  "watchdog",
  sizeof(Watchdog__SetPixelAreaResponse),
  0,
  watchdog__set_pixel_area_response__field_descriptors,
  watchdog__set_pixel_area_response__field_indices_by_name,
  0,  watchdog__set_pixel_area_response__number_ranges,
  (ProtobufCMessageInit) watchdog__set_pixel_area_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__set_display_on_response__field_descriptors NULL
#define watchdog__set_display_on_response__field_indices_by_name NULL
#define watchdog__set_display_on_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__set_display_on_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.SetDisplayOnResponse",
  "SetDisplayOnResponse",
  "Watchdog__SetDisplayOnResponse",
  "watchdog",
  sizeof(Watchdog__SetDisplayOnResponse),
  0,
  watchdog__set_display_on_response__field_descriptors,
  watchdog__set_display_on_response__field_indices_by_name,
  0,  watchdog__set_display_on_response__number_ranges,
  (ProtobufCMessageInit) watchdog__set_display_on_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__function_control_set_response__field_descriptors NULL
#define watchdog__function_control_set_response__field_indices_by_name NULL
#define watchdog__function_control_set_response__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__function_control_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.FunctionControlSetResponse",
  "FunctionControlSetResponse",
  "Watchdog__FunctionControlSetResponse",
  "watchdog",
  sizeof(Watchdog__FunctionControlSetResponse),
  0,
  watchdog__function_control_set_response__field_descriptors,
  watchdog__function_control_set_response__field_indices_by_name,
  0,  watchdog__function_control_set_response__number_ranges,
  (ProtobufCMessageInit) watchdog__function_control_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__stream_control_start__field_descriptors NULL
#define watchdog__stream_control_start__field_indices_by_name NULL
#define watchdog__stream_control_start__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__stream_control_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.StreamControlStart",
  "StreamControlStart",
  "Watchdog__StreamControlStart",
  "watchdog",
  sizeof(Watchdog__StreamControlStart),
  0,
  watchdog__stream_control_start__field_descriptors,
  watchdog__stream_control_start__field_indices_by_name,
  0,  watchdog__stream_control_start__number_ranges,
  (ProtobufCMessageInit) watchdog__stream_control_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define watchdog__stream_data__field_descriptors NULL
#define watchdog__stream_data__field_indices_by_name NULL
#define watchdog__stream_data__number_ranges NULL
const ProtobufCMessageDescriptor watchdog__stream_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "watchdog.StreamData",
  "StreamData",
  "Watchdog__StreamData",
  "watchdog",
  sizeof(Watchdog__StreamData),
  0,
  watchdog__stream_data__field_descriptors,
  watchdog__stream_data__field_indices_by_name,
  0,  watchdog__stream_data__number_ranges,
  (ProtobufCMessageInit) watchdog__stream_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue watchdog__watchdog_strategy__enum_values_by_number[3] =
{
  { "POWERCUT", "WATCHDOG__WATCHDOG_STRATEGY__POWERCUT", 0 },
  { "SHUTDOWN", "WATCHDOG__WATCHDOG_STRATEGY__SHUTDOWN", 1 },
  { "REBOOT", "WATCHDOG__WATCHDOG_STRATEGY__REBOOT", 2 },
};
static const ProtobufCIntRange watchdog__watchdog_strategy__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex watchdog__watchdog_strategy__enum_values_by_name[3] =
{
  { "POWERCUT", 0 },
  { "REBOOT", 2 },
  { "SHUTDOWN", 1 },
};
const ProtobufCEnumDescriptor watchdog__watchdog_strategy__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "watchdog.WatchdogStrategy",
  "WatchdogStrategy",
  "Watchdog__WatchdogStrategy",
  "watchdog",
  3,
  watchdog__watchdog_strategy__enum_values_by_number,
  3,
  watchdog__watchdog_strategy__enum_values_by_name,
  1,
  watchdog__watchdog_strategy__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
