//
//Copyright © 2022 Ci4Rail GmbH <engineering@ci4rail.com>
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: binaryIoTypeB.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	// At least one channel to process is configured for the wrong direction and no input was read resp. no output was written
	Error_BINARYIOTYPEB_WRONG_DIRECTION Error = 0
	// Channel to read/write does not exist
	Error_BINARYIOTYPEB_INVALID_CHANNEL Error = 1
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "BINARYIOTYPEB_WRONG_DIRECTION",
		1: "BINARYIOTYPEB_INVALID_CHANNEL",
	}
	Error_value = map[string]int32{
		"BINARYIOTYPEB_WRONG_DIRECTION": 0,
		"BINARYIOTYPEB_INVALID_CHANNEL": 1,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_binaryIoTypeB_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_binaryIoTypeB_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{0}
}

// ConfigurationSet to pass to Functionblock.Configuration.functionSpecificConfigurationSet hook
type ConfigurationSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationSet) Reset() {
	*x = ConfigurationSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSet) ProtoMessage() {}

func (x *ConfigurationSet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSet.ProtoReflect.Descriptor instead.
func (*ConfigurationSet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{0}
}

// ConfigurationSetResponse to pass to Functionblock.Configuration.functionSpecificConfigurationSetResponse hook
type ConfigurationSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationSetResponse) Reset() {
	*x = ConfigurationSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSetResponse) ProtoMessage() {}

func (x *ConfigurationSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationSetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{1}
}

// ConfigurationGet to pass to Functionblock.Configuration.functionSpecificConfigurationGet hook
type ConfigurationGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationGet) Reset() {
	*x = ConfigurationGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationGet) ProtoMessage() {}

func (x *ConfigurationGet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationGet.ProtoReflect.Descriptor instead.
func (*ConfigurationGet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{2}
}

// ConfigurationGetResponse to pass to Functionblock.ConfigurationGetResponse.functionSpecificConfigurationGetResponse hook
// Returns the current hardware configuration
type ConfigurationGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationGetResponse) Reset() {
	*x = ConfigurationGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationGetResponse) ProtoMessage() {}

func (x *ConfigurationGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationGetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{3}
}

// ConfigurationDescribe to pass to Functionblock.Configuration.functionSpecificConfigurationDescribe hook
type ConfigurationDescribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationDescribe) Reset() {
	*x = ConfigurationDescribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationDescribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationDescribe) ProtoMessage() {}

func (x *ConfigurationDescribe) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationDescribe.ProtoReflect.Descriptor instead.
func (*ConfigurationDescribe) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{4}
}

type ConfigurationDescribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfChannels uint32 `protobuf:"fixed32,1,opt,name=numberOfChannels,proto3" json:"numberOfChannels,omitempty"`
}

func (x *ConfigurationDescribeResponse) Reset() {
	*x = ConfigurationDescribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationDescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationDescribeResponse) ProtoMessage() {}

func (x *ConfigurationDescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationDescribeResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationDescribeResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationDescribeResponse) GetNumberOfChannels() uint32 {
	if x != nil {
		return x.NumberOfChannels
	}
	return 0
}

// ConfigurationResponse to pass to Functionblock.ConfigurationResponse.functionSpecificConfigurationResponse hook
type ConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*ConfigurationResponse_Get
	//	*ConfigurationResponse_Set
	//	*ConfigurationResponse_Describe
	Type isConfigurationResponse_Type `protobuf_oneof:"type"`
}

func (x *ConfigurationResponse) Reset() {
	*x = ConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResponse) ProtoMessage() {}

func (x *ConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{6}
}

func (m *ConfigurationResponse) GetType() isConfigurationResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ConfigurationResponse) GetGet() *ConfigurationGetResponse {
	if x, ok := x.GetType().(*ConfigurationResponse_Get); ok {
		return x.Get
	}
	return nil
}

func (x *ConfigurationResponse) GetSet() *ConfigurationSetResponse {
	if x, ok := x.GetType().(*ConfigurationResponse_Set); ok {
		return x.Set
	}
	return nil
}

func (x *ConfigurationResponse) GetDescribe() *ConfigurationDescribeResponse {
	if x, ok := x.GetType().(*ConfigurationResponse_Describe); ok {
		return x.Describe
	}
	return nil
}

type isConfigurationResponse_Type interface {
	isConfigurationResponse_Type()
}

type ConfigurationResponse_Get struct {
	Get *ConfigurationGetResponse `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type ConfigurationResponse_Set struct {
	Set *ConfigurationSetResponse `protobuf:"bytes,2,opt,name=set,proto3,oneof"`
}

type ConfigurationResponse_Describe struct {
	Describe *ConfigurationDescribeResponse `protobuf:"bytes,3,opt,name=describe,proto3,oneof"`
}

func (*ConfigurationResponse_Get) isConfigurationResponse_Type() {}

func (*ConfigurationResponse_Set) isConfigurationResponse_Type() {}

func (*ConfigurationResponse_Describe) isConfigurationResponse_Type() {}

// ============= FunctionControl =================
// Gets the current value of a single binary channel
type GetSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Specifies the binary input channel (0 - (number of channels - 1))
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *GetSingle) Reset() {
	*x = GetSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingle) ProtoMessage() {}

func (x *GetSingle) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingle.ProtoReflect.Descriptor instead.
func (*GetSingle) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{7}
}

func (x *GetSingle) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// Gets the values of all binary channels
type GetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// mask to define which channels are affected by the get all command. 0 means not set, 1 means set, LSB is Output0
	Mask uint32 `protobuf:"fixed32,1,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *GetAll) Reset() {
	*x = GetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAll) ProtoMessage() {}

func (x *GetAll) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAll.ProtoReflect.Descriptor instead.
func (*GetAll) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{8}
}

func (x *GetAll) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

// FunctionControlGet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlGet hook
type FunctionControlGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*FunctionControlGet_Single
	//	*FunctionControlGet_All
	Type isFunctionControlGet_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlGet) Reset() {
	*x = FunctionControlGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlGet) ProtoMessage() {}

func (x *FunctionControlGet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlGet.ProtoReflect.Descriptor instead.
func (*FunctionControlGet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{9}
}

func (m *FunctionControlGet) GetType() isFunctionControlGet_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlGet) GetSingle() *GetSingle {
	if x, ok := x.GetType().(*FunctionControlGet_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlGet) GetAll() *GetAll {
	if x, ok := x.GetType().(*FunctionControlGet_All); ok {
		return x.All
	}
	return nil
}

type isFunctionControlGet_Type interface {
	isFunctionControlGet_Type()
}

type FunctionControlGet_Single struct {
	Single *GetSingle `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlGet_All struct {
	All *GetAll `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*FunctionControlGet_Single) isFunctionControlGet_Type() {}

func (*FunctionControlGet_All) isFunctionControlGet_Type() {}

// Sets the value of a single binary channel
type SetSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of the binary output channel (0 - (number of channels - 1))
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// State of the binary output channel. false means low, true means high.
	State bool `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SetSingle) Reset() {
	*x = SetSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSingle) ProtoMessage() {}

func (x *SetSingle) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSingle.ProtoReflect.Descriptor instead.
func (*SetSingle) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{10}
}

func (x *SetSingle) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SetSingle) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

// Sets all binary channels
type SetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// binary coded map of input values. 0 means low, 1 means high, LSB is Output0
	Values uint32 `protobuf:"fixed32,1,opt,name=values,proto3" json:"values,omitempty"`
	// mask to define which channels are affected by the set all command. 0 means not set, 1 means set, LSB is Output0
	Mask uint32 `protobuf:"fixed32,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *SetAll) Reset() {
	*x = SetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAll) ProtoMessage() {}

func (x *SetAll) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAll.ProtoReflect.Descriptor instead.
func (*SetAll) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{11}
}

func (x *SetAll) GetValues() uint32 {
	if x != nil {
		return x.Values
	}
	return 0
}

func (x *SetAll) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

// FunctionControlSet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlSet hook
type FunctionControlSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*FunctionControlSet_Single
	//	*FunctionControlSet_All
	Type isFunctionControlSet_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlSet) Reset() {
	*x = FunctionControlSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlSet) ProtoMessage() {}

func (x *FunctionControlSet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlSet.ProtoReflect.Descriptor instead.
func (*FunctionControlSet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{12}
}

func (m *FunctionControlSet) GetType() isFunctionControlSet_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlSet) GetSingle() *SetSingle {
	if x, ok := x.GetType().(*FunctionControlSet_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlSet) GetAll() *SetAll {
	if x, ok := x.GetType().(*FunctionControlSet_All); ok {
		return x.All
	}
	return nil
}

type isFunctionControlSet_Type interface {
	isFunctionControlSet_Type()
}

type FunctionControlSet_Single struct {
	Single *SetSingle `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlSet_All struct {
	All *SetAll `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*FunctionControlSet_Single) isFunctionControlSet_Type() {}

func (*FunctionControlSet_All) isFunctionControlSet_Type() {}

type GetSingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of the binary input channel
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// State for the bianry input channel
	State bool `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *GetSingleResponse) Reset() {
	*x = GetSingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleResponse) ProtoMessage() {}

func (x *GetSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleResponse.ProtoReflect.Descriptor instead.
func (*GetSingleResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{13}
}

func (x *GetSingleResponse) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *GetSingleResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type GetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// binary coded map of input values. 0 means low, 1 means high, LSB is Input0
	Inputs uint32 `protobuf:"fixed32,1,opt,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllResponse) GetInputs() uint32 {
	if x != nil {
		return x.Inputs
	}
	return 0
}

type GetError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=binaryIoTypeB.Error" json:"error,omitempty"`
}

func (x *GetError) Reset() {
	*x = GetError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetError) ProtoMessage() {}

func (x *GetError) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetError.ProtoReflect.Descriptor instead.
func (*GetError) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{15}
}

func (x *GetError) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_BINARYIOTYPEB_WRONG_DIRECTION
}

// FunctionControlGetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlGet hook
type FunctionControlGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*FunctionControlGetResponse_Single
	//	*FunctionControlGetResponse_All
	//	*FunctionControlGetResponse_Error
	Type isFunctionControlGetResponse_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlGetResponse) Reset() {
	*x = FunctionControlGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlGetResponse) ProtoMessage() {}

func (x *FunctionControlGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlGetResponse.ProtoReflect.Descriptor instead.
func (*FunctionControlGetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{16}
}

func (m *FunctionControlGetResponse) GetType() isFunctionControlGetResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlGetResponse) GetSingle() *GetSingleResponse {
	if x, ok := x.GetType().(*FunctionControlGetResponse_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlGetResponse) GetAll() *GetAllResponse {
	if x, ok := x.GetType().(*FunctionControlGetResponse_All); ok {
		return x.All
	}
	return nil
}

func (x *FunctionControlGetResponse) GetError() *GetError {
	if x, ok := x.GetType().(*FunctionControlGetResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isFunctionControlGetResponse_Type interface {
	isFunctionControlGetResponse_Type()
}

type FunctionControlGetResponse_Single struct {
	Single *GetSingleResponse `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlGetResponse_All struct {
	All *GetAllResponse `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

type FunctionControlGetResponse_Error struct {
	Error *GetError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*FunctionControlGetResponse_Single) isFunctionControlGetResponse_Type() {}

func (*FunctionControlGetResponse_All) isFunctionControlGetResponse_Type() {}

func (*FunctionControlGetResponse_Error) isFunctionControlGetResponse_Type() {}

type SetSingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSingleResponse) Reset() {
	*x = SetSingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSingleResponse) ProtoMessage() {}

func (x *SetSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSingleResponse.ProtoReflect.Descriptor instead.
func (*SetSingleResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{17}
}

type SetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAllResponse) Reset() {
	*x = SetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllResponse) ProtoMessage() {}

func (x *SetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllResponse.ProtoReflect.Descriptor instead.
func (*SetAllResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{18}
}

type SetError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=binaryIoTypeB.Error" json:"error,omitempty"`
}

func (x *SetError) Reset() {
	*x = SetError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetError) ProtoMessage() {}

func (x *SetError) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetError.ProtoReflect.Descriptor instead.
func (*SetError) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{19}
}

func (x *SetError) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_BINARYIOTYPEB_WRONG_DIRECTION
}

// FunctionControlSetResponse to pass to Functionblock.FunctionControlResponse.functionSpecificControlSet hook
type FunctionControlSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*FunctionControlSetResponse_Single
	//	*FunctionControlSetResponse_All
	//	*FunctionControlSetResponse_Error
	Type isFunctionControlSetResponse_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlSetResponse) Reset() {
	*x = FunctionControlSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlSetResponse) ProtoMessage() {}

func (x *FunctionControlSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlSetResponse.ProtoReflect.Descriptor instead.
func (*FunctionControlSetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{20}
}

func (m *FunctionControlSetResponse) GetType() isFunctionControlSetResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlSetResponse) GetSingle() *SetSingleResponse {
	if x, ok := x.GetType().(*FunctionControlSetResponse_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlSetResponse) GetAll() *SetAllResponse {
	if x, ok := x.GetType().(*FunctionControlSetResponse_All); ok {
		return x.All
	}
	return nil
}

func (x *FunctionControlSetResponse) GetError() *SetError {
	if x, ok := x.GetType().(*FunctionControlSetResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isFunctionControlSetResponse_Type interface {
	isFunctionControlSetResponse_Type()
}

type FunctionControlSetResponse_Single struct {
	Single *SetSingleResponse `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlSetResponse_All struct {
	All *SetAllResponse `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

type FunctionControlSetResponse_Error struct {
	Error *SetError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*FunctionControlSetResponse_Single) isFunctionControlSetResponse_Type() {}

func (*FunctionControlSetResponse_All) isFunctionControlSetResponse_Type() {}

func (*FunctionControlSetResponse_Error) isFunctionControlSetResponse_Type() {}

// ============= StreamControl ==================
// StreamControlStart to pass to Functionblock.StreamControlStart.functionSpecificStreamControlStart hook
type StreamControlStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamControlStart) Reset() {
	*x = StreamControlStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamControlStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlStart) ProtoMessage() {}

func (x *StreamControlStart) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlStart.ProtoReflect.Descriptor instead.
func (*StreamControlStart) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{21}
}

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{22}
}

// StreamData to pass to Functionblock.StreamData.functionSpecificStreamData hook
type StreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeB_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeB_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeB_proto_rawDescGZIP(), []int{23}
}

var File_binaryIoTypeB_proto protoreflect.FileDescriptor

var file_binaryIoTypeB_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0x4b, 0x0a,
	0x1d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x15, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65,
	0x74, 0x12, 0x3b, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x4a,
	0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2c, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x1c, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x7b, 0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x65, 0x74, 0x12, 0x32, 0x0a,
	0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x7b, 0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x12, 0x32, 0x0a,
	0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x53,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x73, 0x22, 0x36, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xc4, 0x01, 0x0a, 0x1a,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79,
	0x70, 0x65, 0x42, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x08, 0x53, 0x65, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0xc4, 0x01, 0x0a, 0x1a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x2e, 0x53, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x03,
	0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12,
	0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2e, 0x53,
	0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x08,
	0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x4d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x21, 0x0a, 0x1d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x49, 0x4f, 0x54, 0x59, 0x50, 0x45, 0x42,
	0x5f, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x49, 0x4f, 0x54, 0x59,
	0x50, 0x45, 0x42, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x4e, 0x45, 0x4c, 0x10, 0x01, 0x42, 0x18, 0x5a, 0x16, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binaryIoTypeB_proto_rawDescOnce sync.Once
	file_binaryIoTypeB_proto_rawDescData = file_binaryIoTypeB_proto_rawDesc
)

func file_binaryIoTypeB_proto_rawDescGZIP() []byte {
	file_binaryIoTypeB_proto_rawDescOnce.Do(func() {
		file_binaryIoTypeB_proto_rawDescData = protoimpl.X.CompressGZIP(file_binaryIoTypeB_proto_rawDescData)
	})
	return file_binaryIoTypeB_proto_rawDescData
}

var file_binaryIoTypeB_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_binaryIoTypeB_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_binaryIoTypeB_proto_goTypes = []interface{}{
	(Error)(0),                            // 0: binaryIoTypeB.Error
	(*ConfigurationSet)(nil),              // 1: binaryIoTypeB.ConfigurationSet
	(*ConfigurationSetResponse)(nil),      // 2: binaryIoTypeB.ConfigurationSetResponse
	(*ConfigurationGet)(nil),              // 3: binaryIoTypeB.ConfigurationGet
	(*ConfigurationGetResponse)(nil),      // 4: binaryIoTypeB.ConfigurationGetResponse
	(*ConfigurationDescribe)(nil),         // 5: binaryIoTypeB.ConfigurationDescribe
	(*ConfigurationDescribeResponse)(nil), // 6: binaryIoTypeB.ConfigurationDescribeResponse
	(*ConfigurationResponse)(nil),         // 7: binaryIoTypeB.ConfigurationResponse
	(*GetSingle)(nil),                     // 8: binaryIoTypeB.GetSingle
	(*GetAll)(nil),                        // 9: binaryIoTypeB.GetAll
	(*FunctionControlGet)(nil),            // 10: binaryIoTypeB.FunctionControlGet
	(*SetSingle)(nil),                     // 11: binaryIoTypeB.SetSingle
	(*SetAll)(nil),                        // 12: binaryIoTypeB.SetAll
	(*FunctionControlSet)(nil),            // 13: binaryIoTypeB.FunctionControlSet
	(*GetSingleResponse)(nil),             // 14: binaryIoTypeB.GetSingleResponse
	(*GetAllResponse)(nil),                // 15: binaryIoTypeB.GetAllResponse
	(*GetError)(nil),                      // 16: binaryIoTypeB.GetError
	(*FunctionControlGetResponse)(nil),    // 17: binaryIoTypeB.FunctionControlGetResponse
	(*SetSingleResponse)(nil),             // 18: binaryIoTypeB.SetSingleResponse
	(*SetAllResponse)(nil),                // 19: binaryIoTypeB.SetAllResponse
	(*SetError)(nil),                      // 20: binaryIoTypeB.SetError
	(*FunctionControlSetResponse)(nil),    // 21: binaryIoTypeB.FunctionControlSetResponse
	(*StreamControlStart)(nil),            // 22: binaryIoTypeB.StreamControlStart
	(*Sample)(nil),                        // 23: binaryIoTypeB.Sample
	(*StreamData)(nil),                    // 24: binaryIoTypeB.StreamData
}
var file_binaryIoTypeB_proto_depIdxs = []int32{
	4,  // 0: binaryIoTypeB.ConfigurationResponse.get:type_name -> binaryIoTypeB.ConfigurationGetResponse
	2,  // 1: binaryIoTypeB.ConfigurationResponse.set:type_name -> binaryIoTypeB.ConfigurationSetResponse
	6,  // 2: binaryIoTypeB.ConfigurationResponse.describe:type_name -> binaryIoTypeB.ConfigurationDescribeResponse
	8,  // 3: binaryIoTypeB.FunctionControlGet.single:type_name -> binaryIoTypeB.GetSingle
	9,  // 4: binaryIoTypeB.FunctionControlGet.all:type_name -> binaryIoTypeB.GetAll
	11, // 5: binaryIoTypeB.FunctionControlSet.single:type_name -> binaryIoTypeB.SetSingle
	12, // 6: binaryIoTypeB.FunctionControlSet.all:type_name -> binaryIoTypeB.SetAll
	0,  // 7: binaryIoTypeB.GetError.error:type_name -> binaryIoTypeB.Error
	14, // 8: binaryIoTypeB.FunctionControlGetResponse.single:type_name -> binaryIoTypeB.GetSingleResponse
	15, // 9: binaryIoTypeB.FunctionControlGetResponse.all:type_name -> binaryIoTypeB.GetAllResponse
	16, // 10: binaryIoTypeB.FunctionControlGetResponse.error:type_name -> binaryIoTypeB.GetError
	0,  // 11: binaryIoTypeB.SetError.error:type_name -> binaryIoTypeB.Error
	18, // 12: binaryIoTypeB.FunctionControlSetResponse.single:type_name -> binaryIoTypeB.SetSingleResponse
	19, // 13: binaryIoTypeB.FunctionControlSetResponse.all:type_name -> binaryIoTypeB.SetAllResponse
	20, // 14: binaryIoTypeB.FunctionControlSetResponse.error:type_name -> binaryIoTypeB.SetError
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_binaryIoTypeB_proto_init() }
func file_binaryIoTypeB_proto_init() {
	if File_binaryIoTypeB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binaryIoTypeB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationDescribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationDescribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamControlStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeB_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_binaryIoTypeB_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ConfigurationResponse_Get)(nil),
		(*ConfigurationResponse_Set)(nil),
		(*ConfigurationResponse_Describe)(nil),
	}
	file_binaryIoTypeB_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*FunctionControlGet_Single)(nil),
		(*FunctionControlGet_All)(nil),
	}
	file_binaryIoTypeB_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*FunctionControlSet_Single)(nil),
		(*FunctionControlSet_All)(nil),
	}
	file_binaryIoTypeB_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*FunctionControlGetResponse_Single)(nil),
		(*FunctionControlGetResponse_All)(nil),
		(*FunctionControlGetResponse_Error)(nil),
	}
	file_binaryIoTypeB_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*FunctionControlSetResponse_Single)(nil),
		(*FunctionControlSetResponse_All)(nil),
		(*FunctionControlSetResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binaryIoTypeB_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binaryIoTypeB_proto_goTypes,
		DependencyIndexes: file_binaryIoTypeB_proto_depIdxs,
		EnumInfos:         file_binaryIoTypeB_proto_enumTypes,
		MessageInfos:      file_binaryIoTypeB_proto_msgTypes,
	}.Build()
	File_binaryIoTypeB_proto = out.File
	file_binaryIoTypeB_proto_rawDesc = nil
	file_binaryIoTypeB_proto_goTypes = nil
	file_binaryIoTypeB_proto_depIdxs = nil
}
