/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: binaryIoTypeB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "binaryIoTypeB.pb-c.h"
void   binary_io_type_b__configuration_set__init
                     (BinaryIoTypeB__ConfigurationSet         *message)
{
  static const BinaryIoTypeB__ConfigurationSet init_value = BINARY_IO_TYPE_B__CONFIGURATION_SET__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_set__get_packed_size
                     (const BinaryIoTypeB__ConfigurationSet *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_set__pack
                     (const BinaryIoTypeB__ConfigurationSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_set__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationSet *
       binary_io_type_b__configuration_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationSet *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_set__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_set__free_unpacked
                     (BinaryIoTypeB__ConfigurationSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_set_response__init
                     (BinaryIoTypeB__ConfigurationSetResponse         *message)
{
  static const BinaryIoTypeB__ConfigurationSetResponse init_value = BINARY_IO_TYPE_B__CONFIGURATION_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_set_response__get_packed_size
                     (const BinaryIoTypeB__ConfigurationSetResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_set_response__pack
                     (const BinaryIoTypeB__ConfigurationSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_set_response__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationSetResponse *
       binary_io_type_b__configuration_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationSetResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_set_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_set_response__free_unpacked
                     (BinaryIoTypeB__ConfigurationSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_get__init
                     (BinaryIoTypeB__ConfigurationGet         *message)
{
  static const BinaryIoTypeB__ConfigurationGet init_value = BINARY_IO_TYPE_B__CONFIGURATION_GET__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_get__get_packed_size
                     (const BinaryIoTypeB__ConfigurationGet *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_get__pack
                     (const BinaryIoTypeB__ConfigurationGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_get__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationGet *
       binary_io_type_b__configuration_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationGet *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_get__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_get__free_unpacked
                     (BinaryIoTypeB__ConfigurationGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_get_response__init
                     (BinaryIoTypeB__ConfigurationGetResponse         *message)
{
  static const BinaryIoTypeB__ConfigurationGetResponse init_value = BINARY_IO_TYPE_B__CONFIGURATION_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_get_response__get_packed_size
                     (const BinaryIoTypeB__ConfigurationGetResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_get_response__pack
                     (const BinaryIoTypeB__ConfigurationGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_get_response__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationGetResponse *
       binary_io_type_b__configuration_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationGetResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_get_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_get_response__free_unpacked
                     (BinaryIoTypeB__ConfigurationGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_describe__init
                     (BinaryIoTypeB__ConfigurationDescribe         *message)
{
  static const BinaryIoTypeB__ConfigurationDescribe init_value = BINARY_IO_TYPE_B__CONFIGURATION_DESCRIBE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_describe__get_packed_size
                     (const BinaryIoTypeB__ConfigurationDescribe *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_describe__pack
                     (const BinaryIoTypeB__ConfigurationDescribe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_describe__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationDescribe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationDescribe *
       binary_io_type_b__configuration_describe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationDescribe *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_describe__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_describe__free_unpacked
                     (BinaryIoTypeB__ConfigurationDescribe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__channel_config__init
                     (BinaryIoTypeB__ChannelConfig         *message)
{
  static const BinaryIoTypeB__ChannelConfig init_value = BINARY_IO_TYPE_B__CHANNEL_CONFIG__INIT;
  *message = init_value;
}
size_t binary_io_type_b__channel_config__get_packed_size
                     (const BinaryIoTypeB__ChannelConfig *message)
{
  assert(message->base.descriptor == &binary_io_type_b__channel_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__channel_config__pack
                     (const BinaryIoTypeB__ChannelConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__channel_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__channel_config__pack_to_buffer
                     (const BinaryIoTypeB__ChannelConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__channel_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ChannelConfig *
       binary_io_type_b__channel_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ChannelConfig *)
     protobuf_c_message_unpack (&binary_io_type_b__channel_config__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__channel_config__free_unpacked
                     (BinaryIoTypeB__ChannelConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__channel_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_describe_response__init
                     (BinaryIoTypeB__ConfigurationDescribeResponse         *message)
{
  static const BinaryIoTypeB__ConfigurationDescribeResponse init_value = BINARY_IO_TYPE_B__CONFIGURATION_DESCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_describe_response__get_packed_size
                     (const BinaryIoTypeB__ConfigurationDescribeResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_describe_response__pack
                     (const BinaryIoTypeB__ConfigurationDescribeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_describe_response__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationDescribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationDescribeResponse *
       binary_io_type_b__configuration_describe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationDescribeResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_describe_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_describe_response__free_unpacked
                     (BinaryIoTypeB__ConfigurationDescribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_describe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__configuration_response__init
                     (BinaryIoTypeB__ConfigurationResponse         *message)
{
  static const BinaryIoTypeB__ConfigurationResponse init_value = BINARY_IO_TYPE_B__CONFIGURATION_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__configuration_response__get_packed_size
                     (const BinaryIoTypeB__ConfigurationResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__configuration_response__pack
                     (const BinaryIoTypeB__ConfigurationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__configuration_response__pack_to_buffer
                     (const BinaryIoTypeB__ConfigurationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__configuration_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__ConfigurationResponse *
       binary_io_type_b__configuration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__ConfigurationResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__configuration_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__configuration_response__free_unpacked
                     (BinaryIoTypeB__ConfigurationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__configuration_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__get_single__init
                     (BinaryIoTypeB__GetSingle         *message)
{
  static const BinaryIoTypeB__GetSingle init_value = BINARY_IO_TYPE_B__GET_SINGLE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__get_single__get_packed_size
                     (const BinaryIoTypeB__GetSingle *message)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__get_single__pack
                     (const BinaryIoTypeB__GetSingle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__get_single__pack_to_buffer
                     (const BinaryIoTypeB__GetSingle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__GetSingle *
       binary_io_type_b__get_single__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__GetSingle *)
     protobuf_c_message_unpack (&binary_io_type_b__get_single__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__get_single__free_unpacked
                     (BinaryIoTypeB__GetSingle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__get_single__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__get_all__init
                     (BinaryIoTypeB__GetAll         *message)
{
  static const BinaryIoTypeB__GetAll init_value = BINARY_IO_TYPE_B__GET_ALL__INIT;
  *message = init_value;
}
size_t binary_io_type_b__get_all__get_packed_size
                     (const BinaryIoTypeB__GetAll *message)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__get_all__pack
                     (const BinaryIoTypeB__GetAll *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__get_all__pack_to_buffer
                     (const BinaryIoTypeB__GetAll *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__GetAll *
       binary_io_type_b__get_all__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__GetAll *)
     protobuf_c_message_unpack (&binary_io_type_b__get_all__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__get_all__free_unpacked
                     (BinaryIoTypeB__GetAll *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__get_all__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__function_control_get__init
                     (BinaryIoTypeB__FunctionControlGet         *message)
{
  static const BinaryIoTypeB__FunctionControlGet init_value = BINARY_IO_TYPE_B__FUNCTION_CONTROL_GET__INIT;
  *message = init_value;
}
size_t binary_io_type_b__function_control_get__get_packed_size
                     (const BinaryIoTypeB__FunctionControlGet *message)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__function_control_get__pack
                     (const BinaryIoTypeB__FunctionControlGet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__function_control_get__pack_to_buffer
                     (const BinaryIoTypeB__FunctionControlGet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__FunctionControlGet *
       binary_io_type_b__function_control_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__FunctionControlGet *)
     protobuf_c_message_unpack (&binary_io_type_b__function_control_get__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__function_control_get__free_unpacked
                     (BinaryIoTypeB__FunctionControlGet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__function_control_get__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__set_single__init
                     (BinaryIoTypeB__SetSingle         *message)
{
  static const BinaryIoTypeB__SetSingle init_value = BINARY_IO_TYPE_B__SET_SINGLE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__set_single__get_packed_size
                     (const BinaryIoTypeB__SetSingle *message)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__set_single__pack
                     (const BinaryIoTypeB__SetSingle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__set_single__pack_to_buffer
                     (const BinaryIoTypeB__SetSingle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__SetSingle *
       binary_io_type_b__set_single__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__SetSingle *)
     protobuf_c_message_unpack (&binary_io_type_b__set_single__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__set_single__free_unpacked
                     (BinaryIoTypeB__SetSingle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__set_single__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__set_all__init
                     (BinaryIoTypeB__SetAll         *message)
{
  static const BinaryIoTypeB__SetAll init_value = BINARY_IO_TYPE_B__SET_ALL__INIT;
  *message = init_value;
}
size_t binary_io_type_b__set_all__get_packed_size
                     (const BinaryIoTypeB__SetAll *message)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__set_all__pack
                     (const BinaryIoTypeB__SetAll *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__set_all__pack_to_buffer
                     (const BinaryIoTypeB__SetAll *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__SetAll *
       binary_io_type_b__set_all__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__SetAll *)
     protobuf_c_message_unpack (&binary_io_type_b__set_all__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__set_all__free_unpacked
                     (BinaryIoTypeB__SetAll *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__set_all__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__function_control_set__init
                     (BinaryIoTypeB__FunctionControlSet         *message)
{
  static const BinaryIoTypeB__FunctionControlSet init_value = BINARY_IO_TYPE_B__FUNCTION_CONTROL_SET__INIT;
  *message = init_value;
}
size_t binary_io_type_b__function_control_set__get_packed_size
                     (const BinaryIoTypeB__FunctionControlSet *message)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__function_control_set__pack
                     (const BinaryIoTypeB__FunctionControlSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__function_control_set__pack_to_buffer
                     (const BinaryIoTypeB__FunctionControlSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__FunctionControlSet *
       binary_io_type_b__function_control_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__FunctionControlSet *)
     protobuf_c_message_unpack (&binary_io_type_b__function_control_set__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__function_control_set__free_unpacked
                     (BinaryIoTypeB__FunctionControlSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__function_control_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__get_single_response__init
                     (BinaryIoTypeB__GetSingleResponse         *message)
{
  static const BinaryIoTypeB__GetSingleResponse init_value = BINARY_IO_TYPE_B__GET_SINGLE_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__get_single_response__get_packed_size
                     (const BinaryIoTypeB__GetSingleResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__get_single_response__pack
                     (const BinaryIoTypeB__GetSingleResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__get_single_response__pack_to_buffer
                     (const BinaryIoTypeB__GetSingleResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__get_single_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__GetSingleResponse *
       binary_io_type_b__get_single_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__GetSingleResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__get_single_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__get_single_response__free_unpacked
                     (BinaryIoTypeB__GetSingleResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__get_single_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__get_all_response__init
                     (BinaryIoTypeB__GetAllResponse         *message)
{
  static const BinaryIoTypeB__GetAllResponse init_value = BINARY_IO_TYPE_B__GET_ALL_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__get_all_response__get_packed_size
                     (const BinaryIoTypeB__GetAllResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__get_all_response__pack
                     (const BinaryIoTypeB__GetAllResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__get_all_response__pack_to_buffer
                     (const BinaryIoTypeB__GetAllResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__get_all_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__GetAllResponse *
       binary_io_type_b__get_all_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__GetAllResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__get_all_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__get_all_response__free_unpacked
                     (BinaryIoTypeB__GetAllResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__get_all_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__function_control_get_response__init
                     (BinaryIoTypeB__FunctionControlGetResponse         *message)
{
  static const BinaryIoTypeB__FunctionControlGetResponse init_value = BINARY_IO_TYPE_B__FUNCTION_CONTROL_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__function_control_get_response__get_packed_size
                     (const BinaryIoTypeB__FunctionControlGetResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__function_control_get_response__pack
                     (const BinaryIoTypeB__FunctionControlGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__function_control_get_response__pack_to_buffer
                     (const BinaryIoTypeB__FunctionControlGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__FunctionControlGetResponse *
       binary_io_type_b__function_control_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__FunctionControlGetResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__function_control_get_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__function_control_get_response__free_unpacked
                     (BinaryIoTypeB__FunctionControlGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__function_control_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__set_single_response__init
                     (BinaryIoTypeB__SetSingleResponse         *message)
{
  static const BinaryIoTypeB__SetSingleResponse init_value = BINARY_IO_TYPE_B__SET_SINGLE_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__set_single_response__get_packed_size
                     (const BinaryIoTypeB__SetSingleResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__set_single_response__pack
                     (const BinaryIoTypeB__SetSingleResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__set_single_response__pack_to_buffer
                     (const BinaryIoTypeB__SetSingleResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__set_single_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__SetSingleResponse *
       binary_io_type_b__set_single_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__SetSingleResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__set_single_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__set_single_response__free_unpacked
                     (BinaryIoTypeB__SetSingleResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__set_single_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__set_all_response__init
                     (BinaryIoTypeB__SetAllResponse         *message)
{
  static const BinaryIoTypeB__SetAllResponse init_value = BINARY_IO_TYPE_B__SET_ALL_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__set_all_response__get_packed_size
                     (const BinaryIoTypeB__SetAllResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__set_all_response__pack
                     (const BinaryIoTypeB__SetAllResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__set_all_response__pack_to_buffer
                     (const BinaryIoTypeB__SetAllResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__set_all_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__SetAllResponse *
       binary_io_type_b__set_all_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__SetAllResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__set_all_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__set_all_response__free_unpacked
                     (BinaryIoTypeB__SetAllResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__set_all_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__function_control_set_response__init
                     (BinaryIoTypeB__FunctionControlSetResponse         *message)
{
  static const BinaryIoTypeB__FunctionControlSetResponse init_value = BINARY_IO_TYPE_B__FUNCTION_CONTROL_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__function_control_set_response__get_packed_size
                     (const BinaryIoTypeB__FunctionControlSetResponse *message)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__function_control_set_response__pack
                     (const BinaryIoTypeB__FunctionControlSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__function_control_set_response__pack_to_buffer
                     (const BinaryIoTypeB__FunctionControlSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__function_control_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__FunctionControlSetResponse *
       binary_io_type_b__function_control_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__FunctionControlSetResponse *)
     protobuf_c_message_unpack (&binary_io_type_b__function_control_set_response__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__function_control_set_response__free_unpacked
                     (BinaryIoTypeB__FunctionControlSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__function_control_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__stream_control_start__init
                     (BinaryIoTypeB__StreamControlStart         *message)
{
  static const BinaryIoTypeB__StreamControlStart init_value = BINARY_IO_TYPE_B__STREAM_CONTROL_START__INIT;
  *message = init_value;
}
size_t binary_io_type_b__stream_control_start__get_packed_size
                     (const BinaryIoTypeB__StreamControlStart *message)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_control_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__stream_control_start__pack
                     (const BinaryIoTypeB__StreamControlStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_control_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__stream_control_start__pack_to_buffer
                     (const BinaryIoTypeB__StreamControlStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_control_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__StreamControlStart *
       binary_io_type_b__stream_control_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__StreamControlStart *)
     protobuf_c_message_unpack (&binary_io_type_b__stream_control_start__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__stream_control_start__free_unpacked
                     (BinaryIoTypeB__StreamControlStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__stream_control_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__sample__init
                     (BinaryIoTypeB__Sample         *message)
{
  static const BinaryIoTypeB__Sample init_value = BINARY_IO_TYPE_B__SAMPLE__INIT;
  *message = init_value;
}
size_t binary_io_type_b__sample__get_packed_size
                     (const BinaryIoTypeB__Sample *message)
{
  assert(message->base.descriptor == &binary_io_type_b__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__sample__pack
                     (const BinaryIoTypeB__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__sample__pack_to_buffer
                     (const BinaryIoTypeB__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__Sample *
       binary_io_type_b__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__Sample *)
     protobuf_c_message_unpack (&binary_io_type_b__sample__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__sample__free_unpacked
                     (BinaryIoTypeB__Sample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary_io_type_b__stream_data__init
                     (BinaryIoTypeB__StreamData         *message)
{
  static const BinaryIoTypeB__StreamData init_value = BINARY_IO_TYPE_B__STREAM_DATA__INIT;
  *message = init_value;
}
size_t binary_io_type_b__stream_data__get_packed_size
                     (const BinaryIoTypeB__StreamData *message)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary_io_type_b__stream_data__pack
                     (const BinaryIoTypeB__StreamData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary_io_type_b__stream_data__pack_to_buffer
                     (const BinaryIoTypeB__StreamData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary_io_type_b__stream_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BinaryIoTypeB__StreamData *
       binary_io_type_b__stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BinaryIoTypeB__StreamData *)
     protobuf_c_message_unpack (&binary_io_type_b__stream_data__descriptor,
                                allocator, len, data);
}
void   binary_io_type_b__stream_data__free_unpacked
                     (BinaryIoTypeB__StreamData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary_io_type_b__stream_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define binary_io_type_b__configuration_set__field_descriptors NULL
#define binary_io_type_b__configuration_set__field_indices_by_name NULL
#define binary_io_type_b__configuration_set__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__configuration_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationSet",
  "ConfigurationSet",
  "BinaryIoTypeB__ConfigurationSet",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationSet),
  0,
  binary_io_type_b__configuration_set__field_descriptors,
  binary_io_type_b__configuration_set__field_indices_by_name,
  0,  binary_io_type_b__configuration_set__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__configuration_set_response__field_descriptors NULL
#define binary_io_type_b__configuration_set_response__field_indices_by_name NULL
#define binary_io_type_b__configuration_set_response__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__configuration_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationSetResponse",
  "ConfigurationSetResponse",
  "BinaryIoTypeB__ConfigurationSetResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationSetResponse),
  0,
  binary_io_type_b__configuration_set_response__field_descriptors,
  binary_io_type_b__configuration_set_response__field_indices_by_name,
  0,  binary_io_type_b__configuration_set_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__configuration_get__field_descriptors NULL
#define binary_io_type_b__configuration_get__field_indices_by_name NULL
#define binary_io_type_b__configuration_get__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__configuration_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationGet",
  "ConfigurationGet",
  "BinaryIoTypeB__ConfigurationGet",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationGet),
  0,
  binary_io_type_b__configuration_get__field_descriptors,
  binary_io_type_b__configuration_get__field_indices_by_name,
  0,  binary_io_type_b__configuration_get__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__configuration_get_response__field_descriptors NULL
#define binary_io_type_b__configuration_get_response__field_indices_by_name NULL
#define binary_io_type_b__configuration_get_response__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__configuration_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationGetResponse",
  "ConfigurationGetResponse",
  "BinaryIoTypeB__ConfigurationGetResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationGetResponse),
  0,
  binary_io_type_b__configuration_get_response__field_descriptors,
  binary_io_type_b__configuration_get_response__field_indices_by_name,
  0,  binary_io_type_b__configuration_get_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__configuration_describe__field_descriptors NULL
#define binary_io_type_b__configuration_describe__field_indices_by_name NULL
#define binary_io_type_b__configuration_describe__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__configuration_describe__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationDescribe",
  "ConfigurationDescribe",
  "BinaryIoTypeB__ConfigurationDescribe",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationDescribe),
  0,
  binary_io_type_b__configuration_describe__field_descriptors,
  binary_io_type_b__configuration_describe__field_indices_by_name,
  0,  binary_io_type_b__configuration_describe__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_describe__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__channel_config__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__ChannelConfig, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__ChannelConfig, direction),
    &binary_io_type_b__channel_direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__channel_config__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  1,   /* field[1] = direction */
};
static const ProtobufCIntRange binary_io_type_b__channel_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__channel_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ChannelConfig",
  "ChannelConfig",
  "BinaryIoTypeB__ChannelConfig",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ChannelConfig),
  2,
  binary_io_type_b__channel_config__field_descriptors,
  binary_io_type_b__channel_config__field_indices_by_name,
  1,  binary_io_type_b__channel_config__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__channel_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__configuration_describe_response__field_descriptors[1] =
{
  {
    "channelConfig",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__ConfigurationDescribeResponse, n_channelconfig),
    offsetof(BinaryIoTypeB__ConfigurationDescribeResponse, channelconfig),
    &binary_io_type_b__channel_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__configuration_describe_response__field_indices_by_name[] = {
  0,   /* field[0] = channelConfig */
};
static const ProtobufCIntRange binary_io_type_b__configuration_describe_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor binary_io_type_b__configuration_describe_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationDescribeResponse",
  "ConfigurationDescribeResponse",
  "BinaryIoTypeB__ConfigurationDescribeResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationDescribeResponse),
  1,
  binary_io_type_b__configuration_describe_response__field_descriptors,
  binary_io_type_b__configuration_describe_response__field_indices_by_name,
  1,  binary_io_type_b__configuration_describe_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_describe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__configuration_response__field_descriptors[3] =
{
  {
    "get",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__ConfigurationResponse, type_case),
    offsetof(BinaryIoTypeB__ConfigurationResponse, get),
    &binary_io_type_b__configuration_get_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__ConfigurationResponse, type_case),
    offsetof(BinaryIoTypeB__ConfigurationResponse, set),
    &binary_io_type_b__configuration_set_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "describe",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__ConfigurationResponse, type_case),
    offsetof(BinaryIoTypeB__ConfigurationResponse, describe),
    &binary_io_type_b__configuration_describe_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__configuration_response__field_indices_by_name[] = {
  2,   /* field[2] = describe */
  0,   /* field[0] = get */
  1,   /* field[1] = set */
};
static const ProtobufCIntRange binary_io_type_b__configuration_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor binary_io_type_b__configuration_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ConfigurationResponse",
  "ConfigurationResponse",
  "BinaryIoTypeB__ConfigurationResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__ConfigurationResponse),
  3,
  binary_io_type_b__configuration_response__field_descriptors,
  binary_io_type_b__configuration_response__field_indices_by_name,
  1,  binary_io_type_b__configuration_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__configuration_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__get_single__field_descriptors[1] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__GetSingle, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__get_single__field_indices_by_name[] = {
  0,   /* field[0] = channel */
};
static const ProtobufCIntRange binary_io_type_b__get_single__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor binary_io_type_b__get_single__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.GetSingle",
  "GetSingle",
  "BinaryIoTypeB__GetSingle",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__GetSingle),
  1,
  binary_io_type_b__get_single__field_descriptors,
  binary_io_type_b__get_single__field_indices_by_name,
  1,  binary_io_type_b__get_single__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__get_single__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__get_all__field_descriptors[1] =
{
  {
    "mask",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__GetAll, mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__get_all__field_indices_by_name[] = {
  0,   /* field[0] = mask */
};
static const ProtobufCIntRange binary_io_type_b__get_all__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor binary_io_type_b__get_all__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.GetAll",
  "GetAll",
  "BinaryIoTypeB__GetAll",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__GetAll),
  1,
  binary_io_type_b__get_all__field_descriptors,
  binary_io_type_b__get_all__field_indices_by_name,
  1,  binary_io_type_b__get_all__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__get_all__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__function_control_get__field_descriptors[2] =
{
  {
    "single",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlGet, type_case),
    offsetof(BinaryIoTypeB__FunctionControlGet, single),
    &binary_io_type_b__get_single__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlGet, type_case),
    offsetof(BinaryIoTypeB__FunctionControlGet, all),
    &binary_io_type_b__get_all__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__function_control_get__field_indices_by_name[] = {
  1,   /* field[1] = all */
  0,   /* field[0] = single */
};
static const ProtobufCIntRange binary_io_type_b__function_control_get__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__function_control_get__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.FunctionControlGet",
  "FunctionControlGet",
  "BinaryIoTypeB__FunctionControlGet",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__FunctionControlGet),
  2,
  binary_io_type_b__function_control_get__field_descriptors,
  binary_io_type_b__function_control_get__field_indices_by_name,
  1,  binary_io_type_b__function_control_get__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__function_control_get__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__set_single__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__SetSingle, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__SetSingle, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__set_single__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange binary_io_type_b__set_single__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__set_single__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.SetSingle",
  "SetSingle",
  "BinaryIoTypeB__SetSingle",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__SetSingle),
  2,
  binary_io_type_b__set_single__field_descriptors,
  binary_io_type_b__set_single__field_indices_by_name,
  1,  binary_io_type_b__set_single__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__set_single__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__set_all__field_descriptors[2] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__SetAll, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__SetAll, mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__set_all__field_indices_by_name[] = {
  1,   /* field[1] = mask */
  0,   /* field[0] = values */
};
static const ProtobufCIntRange binary_io_type_b__set_all__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__set_all__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.SetAll",
  "SetAll",
  "BinaryIoTypeB__SetAll",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__SetAll),
  2,
  binary_io_type_b__set_all__field_descriptors,
  binary_io_type_b__set_all__field_indices_by_name,
  1,  binary_io_type_b__set_all__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__set_all__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__function_control_set__field_descriptors[2] =
{
  {
    "single",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlSet, type_case),
    offsetof(BinaryIoTypeB__FunctionControlSet, single),
    &binary_io_type_b__set_single__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlSet, type_case),
    offsetof(BinaryIoTypeB__FunctionControlSet, all),
    &binary_io_type_b__set_all__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__function_control_set__field_indices_by_name[] = {
  1,   /* field[1] = all */
  0,   /* field[0] = single */
};
static const ProtobufCIntRange binary_io_type_b__function_control_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__function_control_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.FunctionControlSet",
  "FunctionControlSet",
  "BinaryIoTypeB__FunctionControlSet",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__FunctionControlSet),
  2,
  binary_io_type_b__function_control_set__field_descriptors,
  binary_io_type_b__function_control_set__field_indices_by_name,
  1,  binary_io_type_b__function_control_set__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__function_control_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__get_single_response__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__GetSingleResponse, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__GetSingleResponse, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__get_single_response__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange binary_io_type_b__get_single_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__get_single_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.GetSingleResponse",
  "GetSingleResponse",
  "BinaryIoTypeB__GetSingleResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__GetSingleResponse),
  2,
  binary_io_type_b__get_single_response__field_descriptors,
  binary_io_type_b__get_single_response__field_indices_by_name,
  1,  binary_io_type_b__get_single_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__get_single_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__get_all_response__field_descriptors[1] =
{
  {
    "inputs",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__GetAllResponse, inputs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__get_all_response__field_indices_by_name[] = {
  0,   /* field[0] = inputs */
};
static const ProtobufCIntRange binary_io_type_b__get_all_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor binary_io_type_b__get_all_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.GetAllResponse",
  "GetAllResponse",
  "BinaryIoTypeB__GetAllResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__GetAllResponse),
  1,
  binary_io_type_b__get_all_response__field_descriptors,
  binary_io_type_b__get_all_response__field_indices_by_name,
  1,  binary_io_type_b__get_all_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__get_all_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__function_control_get_response__field_descriptors[2] =
{
  {
    "single",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlGetResponse, type_case),
    offsetof(BinaryIoTypeB__FunctionControlGetResponse, single),
    &binary_io_type_b__get_single_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlGetResponse, type_case),
    offsetof(BinaryIoTypeB__FunctionControlGetResponse, all),
    &binary_io_type_b__get_all_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__function_control_get_response__field_indices_by_name[] = {
  1,   /* field[1] = all */
  0,   /* field[0] = single */
};
static const ProtobufCIntRange binary_io_type_b__function_control_get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__function_control_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.FunctionControlGetResponse",
  "FunctionControlGetResponse",
  "BinaryIoTypeB__FunctionControlGetResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__FunctionControlGetResponse),
  2,
  binary_io_type_b__function_control_get_response__field_descriptors,
  binary_io_type_b__function_control_get_response__field_indices_by_name,
  1,  binary_io_type_b__function_control_get_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__function_control_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__set_single_response__field_descriptors NULL
#define binary_io_type_b__set_single_response__field_indices_by_name NULL
#define binary_io_type_b__set_single_response__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__set_single_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.SetSingleResponse",
  "SetSingleResponse",
  "BinaryIoTypeB__SetSingleResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__SetSingleResponse),
  0,
  binary_io_type_b__set_single_response__field_descriptors,
  binary_io_type_b__set_single_response__field_indices_by_name,
  0,  binary_io_type_b__set_single_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__set_single_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__set_all_response__field_descriptors NULL
#define binary_io_type_b__set_all_response__field_indices_by_name NULL
#define binary_io_type_b__set_all_response__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__set_all_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.SetAllResponse",
  "SetAllResponse",
  "BinaryIoTypeB__SetAllResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__SetAllResponse),
  0,
  binary_io_type_b__set_all_response__field_descriptors,
  binary_io_type_b__set_all_response__field_indices_by_name,
  0,  binary_io_type_b__set_all_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__set_all_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__function_control_set_response__field_descriptors[2] =
{
  {
    "single",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlSetResponse, type_case),
    offsetof(BinaryIoTypeB__FunctionControlSetResponse, single),
    &binary_io_type_b__set_single_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__FunctionControlSetResponse, type_case),
    offsetof(BinaryIoTypeB__FunctionControlSetResponse, all),
    &binary_io_type_b__set_all_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__function_control_set_response__field_indices_by_name[] = {
  1,   /* field[1] = all */
  0,   /* field[0] = single */
};
static const ProtobufCIntRange binary_io_type_b__function_control_set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__function_control_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.FunctionControlSetResponse",
  "FunctionControlSetResponse",
  "BinaryIoTypeB__FunctionControlSetResponse",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__FunctionControlSetResponse),
  2,
  binary_io_type_b__function_control_set_response__field_descriptors,
  binary_io_type_b__function_control_set_response__field_indices_by_name,
  1,  binary_io_type_b__function_control_set_response__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__function_control_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define binary_io_type_b__stream_control_start__field_descriptors NULL
#define binary_io_type_b__stream_control_start__field_indices_by_name NULL
#define binary_io_type_b__stream_control_start__number_ranges NULL
const ProtobufCMessageDescriptor binary_io_type_b__stream_control_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.StreamControlStart",
  "StreamControlStart",
  "BinaryIoTypeB__StreamControlStart",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__StreamControlStart),
  0,
  binary_io_type_b__stream_control_start__field_descriptors,
  binary_io_type_b__stream_control_start__field_indices_by_name,
  0,  binary_io_type_b__stream_control_start__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__stream_control_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__sample__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__Sample, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(BinaryIoTypeB__Sample, inputs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__sample__field_indices_by_name[] = {
  1,   /* field[1] = inputs */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange binary_io_type_b__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor binary_io_type_b__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.Sample",
  "Sample",
  "BinaryIoTypeB__Sample",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__Sample),
  2,
  binary_io_type_b__sample__field_descriptors,
  binary_io_type_b__sample__field_indices_by_name,
  1,  binary_io_type_b__sample__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary_io_type_b__stream_data__field_descriptors[1] =
{
  {
    "samples",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BinaryIoTypeB__StreamData, n_samples),
    offsetof(BinaryIoTypeB__StreamData, samples),
    &binary_io_type_b__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary_io_type_b__stream_data__field_indices_by_name[] = {
  0,   /* field[0] = samples */
};
static const ProtobufCIntRange binary_io_type_b__stream_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor binary_io_type_b__stream_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.StreamData",
  "StreamData",
  "BinaryIoTypeB__StreamData",
  "binaryIoTypeB",
  sizeof(BinaryIoTypeB__StreamData),
  1,
  binary_io_type_b__stream_data__field_descriptors,
  binary_io_type_b__stream_data__field_indices_by_name,
  1,  binary_io_type_b__stream_data__number_ranges,
  (ProtobufCMessageInit) binary_io_type_b__stream_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue binary_io_type_b__channel_direction__enum_values_by_number[3] =
{
  { "BINARYIOTYPEB_INPUT", "BINARY_IO_TYPE_B__CHANNEL_DIRECTION__BINARYIOTYPEB_INPUT", 0 },
  { "BINARYIOTYPEB_OUTPUT", "BINARY_IO_TYPE_B__CHANNEL_DIRECTION__BINARYIOTYPEB_OUTPUT", 1 },
  { "BINARYIOTYPEB_INPUT_OUTPUT", "BINARY_IO_TYPE_B__CHANNEL_DIRECTION__BINARYIOTYPEB_INPUT_OUTPUT", 2 },
};
static const ProtobufCIntRange binary_io_type_b__channel_direction__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex binary_io_type_b__channel_direction__enum_values_by_name[3] =
{
  { "BINARYIOTYPEB_INPUT", 0 },
  { "BINARYIOTYPEB_INPUT_OUTPUT", 2 },
  { "BINARYIOTYPEB_OUTPUT", 1 },
};
const ProtobufCEnumDescriptor binary_io_type_b__channel_direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "binaryIoTypeB.ChannelDirection",
  "ChannelDirection",
  "BinaryIoTypeB__ChannelDirection",
  "binaryIoTypeB",
  3,
  binary_io_type_b__channel_direction__enum_values_by_number,
  3,
  binary_io_type_b__channel_direction__enum_values_by_name,
  1,
  binary_io_type_b__channel_direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
